// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: acp.sql

package sqlcdb

import (
	"context"
)

const appendACPEvent = `-- name: AppendACPEvent :one
INSERT INTO acp_events(conversation_id, kind, body_json) VALUES (?, ?, ?) RETURNING id, conversation_id, kind, body_json
`

type AppendACPEventParams struct {
	ConversationID string `json:"conversation_id"`
	Kind           string `json:"kind"`
	BodyJson       string `json:"body_json"`
}

func (q *Queries) AppendACPEvent(ctx context.Context, arg AppendACPEventParams) (AcpEvent, error) {
	row := q.db.QueryRowContext(ctx, appendACPEvent, arg.ConversationID, arg.Kind, arg.BodyJson)
	var i AcpEvent
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Kind,
		&i.BodyJson,
	)
	return i, err
}

const cancelACPPermissions = `-- name: CancelACPPermissions :exec
UPDATE acp_permissions SET status = 'cancelled', resolved_at = ? WHERE conversation_id = ? AND status = 'pending'
`

type CancelACPPermissionsParams struct {
	ResolvedAt     string `json:"resolved_at"`
	ConversationID string `json:"conversation_id"`
}

func (q *Queries) CancelACPPermissions(ctx context.Context, arg CancelACPPermissionsParams) error {
	_, err := q.db.ExecContext(ctx, cancelACPPermissions, arg.ResolvedAt, arg.ConversationID)
	return err
}

const clearACPGrants = `-- name: ClearACPGrants :exec
DELETE FROM acp_grants WHERE identity = ?
`

func (q *Queries) ClearACPGrants(ctx context.Context, identity string) error {
	_, err := q.db.ExecContext(ctx, clearACPGrants, identity)
	return err
}

const createACPConversation = `-- name: CreateACPConversation :one
INSERT INTO acp_conversations(id, project_id, release_id, automatic, title, profile_json, status, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, project_id, release_id, automatic, title, profile_json, session_id, status, config_json, error, created_at, updated_at
`

type CreateACPConversationParams struct {
	ID          string `json:"id"`
	ProjectID   string `json:"project_id"`
	ReleaseID   string `json:"release_id"`
	Automatic   int64  `json:"automatic"`
	Title       string `json:"title"`
	ProfileJson string `json:"profile_json"`
	Status      string `json:"status"`
	CreatedAt   string `json:"created_at"`
	UpdatedAt   string `json:"updated_at"`
}

func (q *Queries) CreateACPConversation(ctx context.Context, arg CreateACPConversationParams) (AcpConversation, error) {
	row := q.db.QueryRowContext(ctx, createACPConversation,
		arg.ID,
		arg.ProjectID,
		arg.ReleaseID,
		arg.Automatic,
		arg.Title,
		arg.ProfileJson,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i AcpConversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseID,
		&i.Automatic,
		&i.Title,
		&i.ProfileJson,
		&i.SessionID,
		&i.Status,
		&i.ConfigJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createACPPermission = `-- name: CreateACPPermission :one
INSERT INTO acp_permissions(id, conversation_id, request_json, created_at) VALUES (?, ?, ?, ?) RETURNING id, conversation_id, request_json, status, option_id, answered_by, created_at, resolved_at
`

type CreateACPPermissionParams struct {
	ID             string `json:"id"`
	ConversationID string `json:"conversation_id"`
	RequestJson    string `json:"request_json"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) CreateACPPermission(ctx context.Context, arg CreateACPPermissionParams) (AcpPermission, error) {
	row := q.db.QueryRowContext(ctx, createACPPermission,
		arg.ID,
		arg.ConversationID,
		arg.RequestJson,
		arg.CreatedAt,
	)
	var i AcpPermission
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RequestJson,
		&i.Status,
		&i.OptionID,
		&i.AnsweredBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getACPConversation = `-- name: GetACPConversation :one
SELECT id, project_id, release_id, automatic, title, profile_json, session_id, status, config_json, error, created_at, updated_at FROM acp_conversations WHERE id = ?
`

func (q *Queries) GetACPConversation(ctx context.Context, id string) (AcpConversation, error) {
	row := q.db.QueryRowContext(ctx, getACPConversation, id)
	var i AcpConversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ReleaseID,
		&i.Automatic,
		&i.Title,
		&i.ProfileJson,
		&i.SessionID,
		&i.Status,
		&i.ConfigJson,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getACPPermission = `-- name: GetACPPermission :one
SELECT id, conversation_id, request_json, status, option_id, answered_by, created_at, resolved_at FROM acp_permissions WHERE id = ?
`

func (q *Queries) GetACPPermission(ctx context.Context, id string) (AcpPermission, error) {
	row := q.db.QueryRowContext(ctx, getACPPermission, id)
	var i AcpPermission
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RequestJson,
		&i.Status,
		&i.OptionID,
		&i.AnsweredBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getACPSettings = `-- name: GetACPSettings :one
SELECT id, revision, profile_json FROM acp_settings WHERE id = 1
`

func (q *Queries) GetACPSettings(ctx context.Context) (AcpSetting, error) {
	row := q.db.QueryRowContext(ctx, getACPSettings)
	var i AcpSetting
	err := row.Scan(&i.ID, &i.Revision, &i.ProfileJson)
	return i, err
}

const hasACPGrant = `-- name: HasACPGrant :one
SELECT COUNT(*) FROM acp_grants WHERE identity = ? AND tool = ? AND (session_id = '' OR session_id = ?)
`

type HasACPGrantParams struct {
	Identity  string `json:"identity"`
	Tool      string `json:"tool"`
	SessionID string `json:"session_id"`
}

func (q *Queries) HasACPGrant(ctx context.Context, arg HasACPGrantParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasACPGrant, arg.Identity, arg.Tool, arg.SessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const invalidateACPPermissions = `-- name: InvalidateACPPermissions :exec
UPDATE acp_permissions SET status = 'cancelled', resolved_at = ? WHERE status = 'pending'
`

func (q *Queries) InvalidateACPPermissions(ctx context.Context, resolvedAt string) error {
	_, err := q.db.ExecContext(ctx, invalidateACPPermissions, resolvedAt)
	return err
}

const listACPConversations = `-- name: ListACPConversations :many
SELECT id, project_id, release_id, automatic, title, profile_json, session_id, status, config_json, error, created_at, updated_at FROM acp_conversations WHERE project_id = ? ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListACPConversations(ctx context.Context, projectID string) ([]AcpConversation, error) {
	rows, err := q.db.QueryContext(ctx, listACPConversations, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcpConversation
	for rows.Next() {
		var i AcpConversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Automatic,
			&i.Title,
			&i.ProfileJson,
			&i.SessionID,
			&i.Status,
			&i.ConfigJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACPEvents = `-- name: ListACPEvents :many
SELECT id, conversation_id, kind, body_json FROM acp_events WHERE conversation_id = ? AND id > ? ORDER BY id LIMIT 500
`

type ListACPEventsParams struct {
	ConversationID string `json:"conversation_id"`
	ID             int64  `json:"id"`
}

func (q *Queries) ListACPEvents(ctx context.Context, arg ListACPEventsParams) ([]AcpEvent, error) {
	rows, err := q.db.QueryContext(ctx, listACPEvents, arg.ConversationID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcpEvent
	for rows.Next() {
		var i AcpEvent
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Kind,
			&i.BodyJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACPPermissions = `-- name: ListACPPermissions :many
SELECT id, conversation_id, request_json, status, option_id, answered_by, created_at, resolved_at FROM acp_permissions WHERE status = 'pending' ORDER BY created_at, id
`

func (q *Queries) ListACPPermissions(ctx context.Context) ([]AcpPermission, error) {
	rows, err := q.db.QueryContext(ctx, listACPPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcpPermission
	for rows.Next() {
		var i AcpPermission
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.RequestJson,
			&i.Status,
			&i.OptionID,
			&i.AnsweredBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listACPReviewCandidates = `-- name: ListACPReviewCandidates :many
SELECT r.id, r.project_id, p.display_name FROM releases r JOIN projects p ON p.id = r.project_id
WHERE p.auto_build_policy = 'ai'
AND json_extract(r.body_json, '$.update.lastAutomaticStatus') IN ('ai-pending', 'ai-reviewing')
AND COALESCE(json_extract(r.body_json, '$.buildStatus'), '') NOT IN ('building', 'succeeded')
`

type ListACPReviewCandidatesRow struct {
	ID          string `json:"id"`
	ProjectID   string `json:"project_id"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) ListACPReviewCandidates(ctx context.Context) ([]ListACPReviewCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listACPReviewCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListACPReviewCandidatesRow
	for rows.Next() {
		var i ListACPReviewCandidatesRow
		if err := rows.Scan(&i.ID, &i.ProjectID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveACPConversations = `-- name: ListActiveACPConversations :many
SELECT id, project_id, release_id, automatic, title, profile_json, session_id, status, config_json, error, created_at, updated_at FROM acp_conversations WHERE status IN ('starting', 'running', 'waiting')
`

func (q *Queries) ListActiveACPConversations(ctx context.Context) ([]AcpConversation, error) {
	rows, err := q.db.QueryContext(ctx, listActiveACPConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcpConversation
	for rows.Next() {
		var i AcpConversation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Automatic,
			&i.Title,
			&i.ProfileJson,
			&i.SessionID,
			&i.Status,
			&i.ConfigJson,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rememberACPGrant = `-- name: RememberACPGrant :exec
INSERT OR IGNORE INTO acp_grants(identity, tool, session_id) VALUES (?, ?, ?)
`

type RememberACPGrantParams struct {
	Identity  string `json:"identity"`
	Tool      string `json:"tool"`
	SessionID string `json:"session_id"`
}

func (q *Queries) RememberACPGrant(ctx context.Context, arg RememberACPGrantParams) error {
	_, err := q.db.ExecContext(ctx, rememberACPGrant, arg.Identity, arg.Tool, arg.SessionID)
	return err
}

const resolveACPPermission = `-- name: ResolveACPPermission :one
UPDATE acp_permissions SET status = ?, option_id = ?, answered_by = ?, resolved_at = ? WHERE id = ? AND status = 'pending' RETURNING id, conversation_id, request_json, status, option_id, answered_by, created_at, resolved_at
`

type ResolveACPPermissionParams struct {
	Status     string `json:"status"`
	OptionID   string `json:"option_id"`
	AnsweredBy string `json:"answered_by"`
	ResolvedAt string `json:"resolved_at"`
	ID         string `json:"id"`
}

func (q *Queries) ResolveACPPermission(ctx context.Context, arg ResolveACPPermissionParams) (AcpPermission, error) {
	row := q.db.QueryRowContext(ctx, resolveACPPermission,
		arg.Status,
		arg.OptionID,
		arg.AnsweredBy,
		arg.ResolvedAt,
		arg.ID,
	)
	var i AcpPermission
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.RequestJson,
		&i.Status,
		&i.OptionID,
		&i.AnsweredBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const setACPTitle = `-- name: SetACPTitle :exec
UPDATE acp_conversations SET title = ?, updated_at = ? WHERE id = ?
`

type SetACPTitleParams struct {
	Title     string `json:"title"`
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) SetACPTitle(ctx context.Context, arg SetACPTitleParams) error {
	_, err := q.db.ExecContext(ctx, setACPTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}

const updateACPConversation = `-- name: UpdateACPConversation :exec
UPDATE acp_conversations SET session_id = ?, status = ?, config_json = ?, error = ?, updated_at = ? WHERE id = ?
`

type UpdateACPConversationParams struct {
	SessionID  string `json:"session_id"`
	Status     string `json:"status"`
	ConfigJson string `json:"config_json"`
	Error      string `json:"error"`
	UpdatedAt  string `json:"updated_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateACPConversation(ctx context.Context, arg UpdateACPConversationParams) error {
	_, err := q.db.ExecContext(ctx, updateACPConversation,
		arg.SessionID,
		arg.Status,
		arg.ConfigJson,
		arg.Error,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateACPSettings = `-- name: UpdateACPSettings :one
UPDATE acp_settings SET profile_json = ?, revision = revision + 1 WHERE id = 1 AND revision = ? RETURNING id, revision, profile_json
`

type UpdateACPSettingsParams struct {
	ProfileJson string `json:"profile_json"`
	Revision    int64  `json:"revision"`
}

func (q *Queries) UpdateACPSettings(ctx context.Context, arg UpdateACPSettingsParams) (AcpSetting, error) {
	row := q.db.QueryRowContext(ctx, updateACPSettings, arg.ProfileJson, arg.Revision)
	var i AcpSetting
	err := row.Scan(&i.ID, &i.Revision, &i.ProfileJson)
	return i, err
}
