// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlcdb

import (
	"context"
)

const getArtifact = `-- name: GetArtifact :one
SELECT id, sha256, size_bytes, original_filename, kind, created_at
FROM artifacts
WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBySHA256 = `-- name: GetArtifactBySHA256 :one
SELECT id, sha256, size_bytes, original_filename, kind, created_at
FROM artifacts
WHERE sha256 = ?
`

func (q *Queries) GetArtifactBySHA256(ctx context.Context, sha256 string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactBySHA256, sha256)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (
    id, sha256, size_bytes, original_filename, kind, created_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, sha256, size_bytes, original_filename, kind, created_at
`

type InsertArtifactParams struct {
	ID               string `json:"id"`
	Sha256           string `json:"sha256"`
	SizeBytes        int64  `json:"size_bytes"`
	OriginalFilename string `json:"original_filename"`
	Kind             string `json:"kind"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, insertArtifact,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.OriginalFilename,
		arg.Kind,
		arg.CreatedAt,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}
