// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const deleteArtifact = `-- name: DeleteArtifact :exec
DELETE FROM artifacts WHERE id = ?
`

func (q *Queries) DeleteArtifact(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteArtifact, id)
	return err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, sha256, size_bytes, original_filename, kind, created_at
FROM artifacts
WHERE id = ?
`

func (q *Queries) GetArtifact(ctx context.Context, id string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifact, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactBySHA256 = `-- name: GetArtifactBySHA256 :one
SELECT id, sha256, size_bytes, original_filename, kind, created_at
FROM artifacts
WHERE sha256 = ?
`

func (q *Queries) GetArtifactBySHA256(ctx context.Context, sha256 string) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, getArtifactBySHA256, sha256)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (
    id, sha256, size_bytes, original_filename, kind, created_at
) VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, sha256, size_bytes, original_filename, kind, created_at
`

type InsertArtifactParams struct {
	ID               string `json:"id"`
	Sha256           string `json:"sha256"`
	SizeBytes        int64  `json:"size_bytes"`
	OriginalFilename string `json:"original_filename"`
	Kind             string `json:"kind"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRowContext(ctx, insertArtifact,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.OriginalFilename,
		arg.Kind,
		arg.CreatedAt,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.OriginalFilename,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listAllReleaseArtifactIDs = `-- name: ListAllReleaseArtifactIDs :many
SELECT artifact_id FROM release_artifacts
`

func (q *Queries) ListAllReleaseArtifactIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllReleaseArtifactIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var artifact_id string
		if err := rows.Scan(&artifact_id); err != nil {
			return nil, err
		}
		items = append(items, artifact_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT id, sha256, size_bytes, original_filename, kind, created_at
FROM artifacts
`

func (q *Queries) ListArtifacts(ctx context.Context) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIconArtifactIDs = `-- name: ListProjectIconArtifactIDs :many
SELECT icon_artifact_id FROM projects WHERE icon_artifact_id IS NOT NULL
`

func (q *Queries) ListProjectIconArtifactIDs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listProjectIconArtifactIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var icon_artifact_id sql.NullString
		if err := rows.Scan(&icon_artifact_id); err != nil {
			return nil, err
		}
		items = append(items, icon_artifact_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceArtifactIDs = `-- name: ListSourceArtifactIDs :many
SELECT source_artifact_id FROM releases WHERE source_artifact_id IS NOT NULL
`

func (q *Queries) ListSourceArtifactIDs(ctx context.Context) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, listSourceArtifactIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var source_artifact_id sql.NullString
		if err := rows.Scan(&source_artifact_id); err != nil {
			return nil, err
		}
		items = append(items, source_artifact_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
