// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlcdb

import (
	"context"
)

const deleteCredentialMeta = `-- name: DeleteCredentialMeta :exec
DELETE FROM credentials WHERE name = ?
`

func (q *Queries) DeleteCredentialMeta(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deleteCredentialMeta, name)
	return err
}

const getCredentialMeta = `-- name: GetCredentialMeta :one
SELECT name, updated_at FROM credentials WHERE name = ?
`

func (q *Queries) GetCredentialMeta(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialMeta, name)
	var i Credential
	err := row.Scan(&i.Name, &i.UpdatedAt)
	return i, err
}

const listCredentialNames = `-- name: ListCredentialNames :many
SELECT name, updated_at FROM credentials ORDER BY name
`

func (q *Queries) ListCredentialNames(ctx context.Context) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(&i.Name, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO credentials (name, updated_at) VALUES (?, ?)
ON CONFLICT (name) DO UPDATE SET updated_at = excluded.updated_at
`

type UpsertCredentialParams struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredential, arg.Name, arg.UpdatedAt)
	return err
}
