// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const countJobsByKind = `-- name: CountJobsByKind :one
SELECT COUNT(*)
FROM jobs
WHERE kind = ?
`

func (q *Queries) CountJobsByKind(ctx context.Context, kind string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJobsByKind, kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, status, project_id, release_id, payload_json, error, log_offset,
       message, current, total, failed_items, paused_items, created_at, started_at, finished_at
FROM jobs
WHERE id = ?
`

func (q *Queries) GetJob(ctx context.Context, id string) (Job, error) {
	row := q.db.QueryRowContext(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ProjectID,
		&i.ReleaseID,
		&i.PayloadJson,
		&i.Error,
		&i.LogOffset,
		&i.Message,
		&i.Current,
		&i.Total,
		&i.FailedItems,
		&i.PausedItems,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestLibraryJobCreatedAt = `-- name: GetLatestLibraryJobCreatedAt :one
SELECT created_at
FROM jobs
WHERE kind = ?
  AND COALESCE(json_extract(payload_json, '$.release_id'), '') = ''
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestLibraryJobCreatedAt(ctx context.Context, kind string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestLibraryJobCreatedAt, kind)
	var created_at string
	err := row.Scan(&created_at)
	return created_at, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (
    id, kind, status, project_id, release_id, payload_json, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, kind, status, project_id, release_id, payload_json, error, log_offset,
          message, current, total, failed_items, paused_items, created_at, started_at, finished_at
`

type InsertJobParams struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	ProjectID   sql.NullString `json:"project_id"`
	ReleaseID   sql.NullString `json:"release_id"`
	PayloadJson string         `json:"payload_json"`
	CreatedAt   string         `json:"created_at"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.ID,
		arg.Kind,
		arg.Status,
		arg.ProjectID,
		arg.ReleaseID,
		arg.PayloadJson,
		arg.CreatedAt,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ProjectID,
		&i.ReleaseID,
		&i.PayloadJson,
		&i.Error,
		&i.LogOffset,
		&i.Message,
		&i.Current,
		&i.Total,
		&i.FailedItems,
		&i.PausedItems,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const interruptRunningJobs = `-- name: InterruptRunningJobs :exec
UPDATE jobs
SET status = 'interrupted',
    error = 'interrupted by daemon restart',
    finished_at = ?
WHERE status = 'running'
`

func (q *Queries) InterruptRunningJobs(ctx context.Context, finishedAt sql.NullString) error {
	_, err := q.db.ExecContext(ctx, interruptRunningJobs, finishedAt)
	return err
}

const listActiveJobsByKind = `-- name: ListActiveJobsByKind :many
SELECT id, kind, status, project_id, release_id, payload_json, error, log_offset,
       message, current, total, failed_items, paused_items, created_at, started_at, finished_at
FROM jobs
WHERE kind = ? AND status IN ('queued', 'running')
ORDER BY created_at
`

func (q *Queries) ListActiveJobsByKind(ctx context.Context, kind string) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Status,
			&i.ProjectID,
			&i.ReleaseID,
			&i.PayloadJson,
			&i.Error,
			&i.LogOffset,
			&i.Message,
			&i.Current,
			&i.Total,
			&i.FailedItems,
			&i.PausedItems,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJob = `-- name: UpdateJob :one
UPDATE jobs
SET status = ?,
    error = ?,
    log_offset = ?,
    started_at = ?,
    finished_at = ?,
    project_id = ?,
    release_id = ?,
    message = ?,
    current = ?,
    total = ?,
    failed_items = ?,
    paused_items = ?
WHERE id = ?
RETURNING id, kind, status, project_id, release_id, payload_json, error, log_offset,
          message, current, total, failed_items, paused_items, created_at, started_at, finished_at
`

type UpdateJobParams struct {
	Status      string         `json:"status"`
	Error       string         `json:"error"`
	LogOffset   int64          `json:"log_offset"`
	StartedAt   sql.NullString `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
	ProjectID   sql.NullString `json:"project_id"`
	ReleaseID   sql.NullString `json:"release_id"`
	Message     string         `json:"message"`
	Current     int64          `json:"current"`
	Total       int64          `json:"total"`
	FailedItems int64          `json:"failed_items"`
	PausedItems int64          `json:"paused_items"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, updateJob,
		arg.Status,
		arg.Error,
		arg.LogOffset,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ProjectID,
		arg.ReleaseID,
		arg.Message,
		arg.Current,
		arg.Total,
		arg.FailedItems,
		arg.PausedItems,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Status,
		&i.ProjectID,
		&i.ReleaseID,
		&i.PayloadJson,
		&i.Error,
		&i.LogOffset,
		&i.Message,
		&i.Current,
		&i.Total,
		&i.FailedItems,
		&i.PausedItems,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
