// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
)

type Artifact struct {
	ID               string `json:"id"`
	Sha256           string `json:"sha256"`
	SizeBytes        int64  `json:"size_bytes"`
	OriginalFilename string `json:"original_filename"`
	Kind             string `json:"kind"`
	CreatedAt        string `json:"created_at"`
}

type Build struct {
	ID         string         `json:"id"`
	ReleaseID  string         `json:"release_id"`
	Status     string         `json:"status"`
	LogText    string         `json:"log_text"`
	StartedAt  sql.NullString `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
}

type BuildArtifact struct {
	BuildID    string `json:"build_id"`
	ArtifactID string `json:"artifact_id"`
}

type Client struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	CertPem    string `json:"cert_pem"`
	CertSha256 string `json:"cert_sha256"`
	Revoked    int64  `json:"revoked"`
	CreatedAt  string `json:"created_at"`
}

type Credential struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

type Job struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	ProjectID   sql.NullString `json:"project_id"`
	ReleaseID   sql.NullString `json:"release_id"`
	PayloadJson string         `json:"payload_json"`
	Error       string         `json:"error"`
	LogOffset   int64          `json:"log_offset"`
	Message     string         `json:"message"`
	Current     int64          `json:"current"`
	Total       int64          `json:"total"`
	FailedItems int64          `json:"failed_items"`
	PausedItems int64          `json:"paused_items"`
	CreatedAt   string         `json:"created_at"`
	StartedAt   sql.NullString `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
}

type LibrarySetting struct {
	ID                       int64  `json:"id"`
	Revision                 int64  `json:"revision"`
	AiProvider               string `json:"ai_provider"`
	AiModel                  string `json:"ai_model"`
	AiReasoningEffort        string `json:"ai_reasoning_effort"`
	AiExecutionMode          string `json:"ai_execution_mode"`
	AiAutoResolve            int64  `json:"ai_auto_resolve"`
	UpdatesEnabled           int64  `json:"updates_enabled"`
	UpdatesDaily             int64  `json:"updates_daily"`
	UpdatesWeekday           int64  `json:"updates_weekday"`
	UpdatesHour              int64  `json:"updates_hour"`
	UpdatesMinute            int64  `json:"updates_minute"`
	UpdatesAutoPrepare       int64  `json:"updates_auto_prepare"`
	RetainedPackageVersions  int64  `json:"retained_package_versions"`
	RetainedCompleteReleases int64  `json:"retained_complete_releases"`
	RetentionDays            int64  `json:"retention_days"`
	RetentionVersions        int64  `json:"retention_versions"`
	BuildParallelism         int64  `json:"build_parallelism"`
}

type Project struct {
	ID                   string         `json:"id"`
	Revision             int64          `json:"revision"`
	DisplayName          string         `json:"display_name"`
	ArchPackageName      string         `json:"arch_package_name"`
	VendorName           string         `json:"vendor_name"`
	SourceIdentity       string         `json:"source_identity"`
	IconArtifactID       sql.NullString `json:"icon_artifact_id"`
	IconSha256           string         `json:"icon_sha256"`
	HistoryJson          string         `json:"history_json"`
	CreatedAt            string         `json:"created_at"`
	ModifiedAt           string         `json:"modified_at"`
	RepoPublish          int64          `json:"repo_publish"`
	RepoPkgnameOverride  string         `json:"repo_pkgname_override"`
	RepoPublishedPkgname string         `json:"repo_published_pkgname"`
	AutoBuildPolicy      string         `json:"auto_build_policy"`
	CompileCachePolicy   string         `json:"compile_cache_policy"`
}

type ProjectRepoPolicy struct {
	ProjectID           string `json:"project_id"`
	StableEnabled       int64  `json:"stable_enabled"`
	AutomaticSoak       int64  `json:"automatic_soak"`
	SoakSecondsOverride int64  `json:"soak_seconds_override"`
}

type Registration struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Status     string         `json:"status"`
	CsrPem     string         `json:"csr_pem"`
	CertPem    string         `json:"cert_pem"`
	ClientID   sql.NullString `json:"client_id"`
	CreatedAt  string         `json:"created_at"`
	ExpiresAt  string         `json:"expires_at"`
	RemoteAddr string         `json:"remote_addr"`
}

type Release struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	Revision         int64          `json:"revision"`
	State            string         `json:"state"`
	SourceType       string         `json:"source_type"`
	VendorVersion    string         `json:"vendor_version"`
	OriginalFilename string         `json:"original_filename"`
	SourceSha256     string         `json:"source_sha256"`
	SourceArtifactID sql.NullString `json:"source_artifact_id"`
	ArchPackageName  string         `json:"arch_package_name"`
	ArchPkgrel       int64          `json:"arch_pkgrel"`
	BodyJson         string         `json:"body_json"`
	CreatedAt        string         `json:"created_at"`
	ModifiedAt       string         `json:"modified_at"`
}

type ReleaseArtifact struct {
	ReleaseID  string `json:"release_id"`
	ArtifactID string `json:"artifact_id"`
	Role       string `json:"role"`
}

type RepoChannelEntry struct {
	Channel       string         `json:"channel"`
	Arch          string         `json:"arch"`
	Pkgname       string         `json:"pkgname"`
	ProjectID     sql.NullString `json:"project_id"`
	ReleaseID     sql.NullString `json:"release_id"`
	Epoch         int64          `json:"epoch"`
	Pkgver        string         `json:"pkgver"`
	Pkgrel        string         `json:"pkgrel"`
	ArtifactID    string         `json:"artifact_id"`
	SigArtifactID sql.NullString `json:"sig_artifact_id"`
	Filename      string         `json:"filename"`
	PublishedAt   string         `json:"published_at"`
}

type RepoDatabase struct {
	Channel            string         `json:"channel"`
	Arch               string         `json:"arch"`
	DbArtifactID       string         `json:"db_artifact_id"`
	DbSigArtifactID    sql.NullString `json:"db_sig_artifact_id"`
	FilesArtifactID    sql.NullString `json:"files_artifact_id"`
	FilesSigArtifactID sql.NullString `json:"files_sig_artifact_id"`
	GeneratedAt        string         `json:"generated_at"`
}

type RepoPackage struct {
	Pkgname         string         `json:"pkgname"`
	ProjectID       sql.NullString `json:"project_id"`
	OriginalPkgname string         `json:"original_pkgname"`
	Internal        int64          `json:"internal"`
	CreatedAt       string         `json:"created_at"`
}

type RepoSetting struct {
	ID                          int64          `json:"id"`
	Revision                    int64          `json:"revision"`
	Enabled                     int64          `json:"enabled"`
	ListenHosts                 string         `json:"listen_hosts"`
	ListenPort                  int64          `json:"listen_port"`
	AdvertisedUrl               string         `json:"advertised_url"`
	StableEnabled               int64          `json:"stable_enabled"`
	SoakSeconds                 int64          `json:"soak_seconds"`
	PackageNamePrefix           string         `json:"package_name_prefix"`
	TrustMode                   string         `json:"trust_mode"`
	SigningFingerprint          string         `json:"signing_fingerprint"`
	SigningInitialized          int64          `json:"signing_initialized"`
	SigningPubkeyArtifactID     sql.NullString `json:"signing_pubkey_artifact_id"`
	RootPubkeyArtifactID        sql.NullString `json:"root_pubkey_artifact_id"`
	RootFingerprint             string         `json:"root_fingerprint"`
	CertifiedPubkeyArtifactID   sql.NullString `json:"certified_pubkey_artifact_id"`
	KeyringGpgArtifactID        sql.NullString `json:"keyring_gpg_artifact_id"`
	KeyringTrustedArtifactID    sql.NullString `json:"keyring_trusted_artifact_id"`
	KeyringRevokedArtifactID    sql.NullString `json:"keyring_revoked_artifact_id"`
	KeyringPackageArtifactID    sql.NullString `json:"keyring_package_artifact_id"`
	KeyringPackageSigArtifactID sql.NullString `json:"keyring_package_sig_artifact_id"`
	KeyringVersion              int64          `json:"keyring_version"`
	ModifiedAt                  string         `json:"modified_at"`
}

type RepoSoak struct {
	Pkgname       string         `json:"pkgname"`
	Arch          string         `json:"arch"`
	Pkgver        string         `json:"pkgver"`
	ProjectID     sql.NullString `json:"project_id"`
	ReleaseID     sql.NullString `json:"release_id"`
	Epoch         int64          `json:"epoch"`
	Pkgrel        string         `json:"pkgrel"`
	ArtifactID    string         `json:"artifact_id"`
	SigArtifactID sql.NullString `json:"sig_artifact_id"`
	SoakStartedAt string         `json:"soak_started_at"`
	EligibleAt    string         `json:"eligible_at"`
	Status        string         `json:"status"`
}

type ServerState struct {
	ID            int64  `json:"id"`
	CreatedAt     string `json:"created_at"`
	SchemaKind    string `json:"schema_kind"`
	SecretBackend string `json:"secret_backend"`
	PkiReady      int64  `json:"pki_ready"`
	ListenEnabled int64  `json:"listen_enabled"`
	ListenPort    int64  `json:"listen_port"`
	ListenHosts   string `json:"listen_hosts"`
}

type UpdateCheckState struct {
	UpdateSourceID    string `json:"update_source_id"`
	LastCheckedAt     string `json:"last_checked_at"`
	LastMessage       string `json:"last_message"`
	LastError         string `json:"last_error"`
	DetectedVersion   string `json:"detected_version"`
	DetectedFilename  string `json:"detected_filename"`
	DetectedSha256    string `json:"detected_sha256"`
	DetectedUrl       string `json:"detected_url"`
	Etag              string `json:"etag"`
	SignatureVerified int64  `json:"signature_verified"`
	JobID             string `json:"job_id"`
}

type UpdateSource struct {
	ID         string `json:"id"`
	ReleaseID  string `json:"release_id"`
	Revision   int64  `json:"revision"`
	Strategy   string `json:"strategy"`
	ConfigJson string `json:"config_json"`
}
