// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
)

type Artifact struct {
	ID               string `json:"id"`
	Sha256           string `json:"sha256"`
	SizeBytes        int64  `json:"size_bytes"`
	OriginalFilename string `json:"original_filename"`
	Kind             string `json:"kind"`
	CreatedAt        string `json:"created_at"`
}

type Build struct {
	ID         string         `json:"id"`
	ReleaseID  string         `json:"release_id"`
	Status     string         `json:"status"`
	LogText    string         `json:"log_text"`
	StartedAt  sql.NullString `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
}

type Client struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	CertPem    string `json:"cert_pem"`
	CertSha256 string `json:"cert_sha256"`
	Revoked    int64  `json:"revoked"`
	CreatedAt  string `json:"created_at"`
}

type Credential struct {
	Name      string `json:"name"`
	UpdatedAt string `json:"updated_at"`
}

type Job struct {
	ID          string         `json:"id"`
	Kind        string         `json:"kind"`
	Status      string         `json:"status"`
	ProjectID   sql.NullString `json:"project_id"`
	ReleaseID   sql.NullString `json:"release_id"`
	PayloadJson string         `json:"payload_json"`
	Error       string         `json:"error"`
	LogOffset   int64          `json:"log_offset"`
	CreatedAt   string         `json:"created_at"`
	StartedAt   sql.NullString `json:"started_at"`
	FinishedAt  sql.NullString `json:"finished_at"`
}

type LibrarySetting struct {
	ID                       int64  `json:"id"`
	Revision                 int64  `json:"revision"`
	AiProvider               string `json:"ai_provider"`
	AiModel                  string `json:"ai_model"`
	AiReasoningEffort        string `json:"ai_reasoning_effort"`
	AiExecutionMode          string `json:"ai_execution_mode"`
	AiAutoResolve            int64  `json:"ai_auto_resolve"`
	UpdatesEnabled           int64  `json:"updates_enabled"`
	UpdatesDaily             int64  `json:"updates_daily"`
	UpdatesWeekday           int64  `json:"updates_weekday"`
	UpdatesHour              int64  `json:"updates_hour"`
	UpdatesMinute            int64  `json:"updates_minute"`
	UpdatesAutoPrepare       int64  `json:"updates_auto_prepare"`
	RetainedPackageVersions  int64  `json:"retained_package_versions"`
	RetainedCompleteReleases int64  `json:"retained_complete_releases"`
}

type Project struct {
	ID              string         `json:"id"`
	Revision        int64          `json:"revision"`
	DisplayName     string         `json:"display_name"`
	ArchPackageName string         `json:"arch_package_name"`
	VendorName      string         `json:"vendor_name"`
	SourceIdentity  string         `json:"source_identity"`
	IconArtifactID  sql.NullString `json:"icon_artifact_id"`
	IconSha256      string         `json:"icon_sha256"`
	HistoryJson     string         `json:"history_json"`
	CreatedAt       string         `json:"created_at"`
	ModifiedAt      string         `json:"modified_at"`
}

type Registration struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Status     string         `json:"status"`
	CsrPem     string         `json:"csr_pem"`
	CertPem    string         `json:"cert_pem"`
	ClientID   sql.NullString `json:"client_id"`
	CreatedAt  string         `json:"created_at"`
	ExpiresAt  string         `json:"expires_at"`
	RemoteAddr string         `json:"remote_addr"`
}

type Release struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	Revision         int64          `json:"revision"`
	State            string         `json:"state"`
	SourceType       string         `json:"source_type"`
	VendorVersion    string         `json:"vendor_version"`
	OriginalFilename string         `json:"original_filename"`
	SourceSha256     string         `json:"source_sha256"`
	SourceArtifactID sql.NullString `json:"source_artifact_id"`
	ArchPackageName  string         `json:"arch_package_name"`
	ArchPkgrel       int64          `json:"arch_pkgrel"`
	BodyJson         string         `json:"body_json"`
	CreatedAt        string         `json:"created_at"`
	ModifiedAt       string         `json:"modified_at"`
}

type ReleaseArtifact struct {
	ReleaseID  string `json:"release_id"`
	ArtifactID string `json:"artifact_id"`
	Role       string `json:"role"`
}

type ServerState struct {
	ID            int64  `json:"id"`
	CreatedAt     string `json:"created_at"`
	SchemaKind    string `json:"schema_kind"`
	SecretBackend string `json:"secret_backend"`
	PkiReady      int64  `json:"pki_ready"`
	ListenEnabled int64  `json:"listen_enabled"`
	ListenPort    int64  `json:"listen_port"`
	ListenHosts   string `json:"listen_hosts"`
}

type UpdateCheckState struct {
	UpdateSourceID    string `json:"update_source_id"`
	LastCheckedAt     string `json:"last_checked_at"`
	LastMessage       string `json:"last_message"`
	LastError         string `json:"last_error"`
	DetectedVersion   string `json:"detected_version"`
	DetectedFilename  string `json:"detected_filename"`
	DetectedSha256    string `json:"detected_sha256"`
	DetectedUrl       string `json:"detected_url"`
	Etag              string `json:"etag"`
	SignatureVerified int64  `json:"signature_verified"`
	JobID             string `json:"job_id"`
}

type UpdateSource struct {
	ID         string `json:"id"`
	ReleaseID  string `json:"release_id"`
	Revision   int64  `json:"revision"`
	Strategy   string `json:"strategy"`
	ConfigJson string `json:"config_json"`
}
