// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pki.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const countPendingRegistrations = `-- name: CountPendingRegistrations :one
SELECT COUNT(*) FROM registrations WHERE status = 'pending'
`

func (q *Queries) CountPendingRegistrations(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingRegistrations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getClient = `-- name: GetClient :one
SELECT id, name, cert_pem, cert_sha256, revoked, created_at
FROM clients
WHERE id = ?
`

func (q *Queries) GetClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertPem,
		&i.CertSha256,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getClientByCertSHA256 = `-- name: GetClientByCertSHA256 :one
SELECT id, name, cert_pem, cert_sha256, revoked, created_at
FROM clients
WHERE cert_sha256 = ?
`

func (q *Queries) GetClientByCertSHA256(ctx context.Context, certSha256 string) (Client, error) {
	row := q.db.QueryRowContext(ctx, getClientByCertSHA256, certSha256)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertPem,
		&i.CertSha256,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const getRegistration = `-- name: GetRegistration :one
SELECT id, name, status, csr_pem, cert_pem, client_id, created_at, expires_at, remote_addr
FROM registrations
WHERE id = ?
`

func (q *Queries) GetRegistration(ctx context.Context, id string) (Registration, error) {
	row := q.db.QueryRowContext(ctx, getRegistration, id)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CsrPem,
		&i.CertPem,
		&i.ClientID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RemoteAddr,
	)
	return i, err
}

const insertClient = `-- name: InsertClient :one
INSERT INTO clients (id, name, cert_pem, cert_sha256, revoked, created_at)
VALUES (?, ?, ?, ?, 0, ?)
RETURNING id, name, cert_pem, cert_sha256, revoked, created_at
`

type InsertClientParams struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	CertPem    string `json:"cert_pem"`
	CertSha256 string `json:"cert_sha256"`
	CreatedAt  string `json:"created_at"`
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (Client, error) {
	row := q.db.QueryRowContext(ctx, insertClient,
		arg.ID,
		arg.Name,
		arg.CertPem,
		arg.CertSha256,
		arg.CreatedAt,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertPem,
		&i.CertSha256,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const insertRegistration = `-- name: InsertRegistration :one
INSERT INTO registrations (
    id, name, status, csr_pem, cert_pem, client_id, created_at, expires_at, remote_addr
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, name, status, csr_pem, cert_pem, client_id, created_at, expires_at, remote_addr
`

type InsertRegistrationParams struct {
	ID         string         `json:"id"`
	Name       string         `json:"name"`
	Status     string         `json:"status"`
	CsrPem     string         `json:"csr_pem"`
	CertPem    string         `json:"cert_pem"`
	ClientID   sql.NullString `json:"client_id"`
	CreatedAt  string         `json:"created_at"`
	ExpiresAt  string         `json:"expires_at"`
	RemoteAddr string         `json:"remote_addr"`
}

func (q *Queries) InsertRegistration(ctx context.Context, arg InsertRegistrationParams) (Registration, error) {
	row := q.db.QueryRowContext(ctx, insertRegistration,
		arg.ID,
		arg.Name,
		arg.Status,
		arg.CsrPem,
		arg.CertPem,
		arg.ClientID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.RemoteAddr,
	)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CsrPem,
		&i.CertPem,
		&i.ClientID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RemoteAddr,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, cert_pem, cert_sha256, revoked, created_at
FROM clients
ORDER BY created_at
`

func (q *Queries) ListClients(ctx context.Context) ([]Client, error) {
	rows, err := q.db.QueryContext(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CertPem,
			&i.CertSha256,
			&i.Revoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRegistrations = `-- name: ListPendingRegistrations :many
SELECT id, name, status, csr_pem, cert_pem, client_id, created_at, expires_at, remote_addr
FROM registrations
WHERE status = 'pending'
ORDER BY created_at
`

func (q *Queries) ListPendingRegistrations(ctx context.Context) ([]Registration, error) {
	rows, err := q.db.QueryContext(ctx, listPendingRegistrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Registration
	for rows.Next() {
		var i Registration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CsrPem,
			&i.CertPem,
			&i.ClientID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RemoteAddr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeClient = `-- name: RevokeClient :one
UPDATE clients
SET revoked = 1
WHERE id = ?
RETURNING id, name, cert_pem, cert_sha256, revoked, created_at
`

func (q *Queries) RevokeClient(ctx context.Context, id string) (Client, error) {
	row := q.db.QueryRowContext(ctx, revokeClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CertPem,
		&i.CertSha256,
		&i.Revoked,
		&i.CreatedAt,
	)
	return i, err
}

const updateRegistration = `-- name: UpdateRegistration :one
UPDATE registrations
SET status = ?,
    cert_pem = ?,
    client_id = ?
WHERE id = ?
RETURNING id, name, status, csr_pem, cert_pem, client_id, created_at, expires_at, remote_addr
`

type UpdateRegistrationParams struct {
	Status   string         `json:"status"`
	CertPem  string         `json:"cert_pem"`
	ClientID sql.NullString `json:"client_id"`
	ID       string         `json:"id"`
}

func (q *Queries) UpdateRegistration(ctx context.Context, arg UpdateRegistrationParams) (Registration, error) {
	row := q.db.QueryRowContext(ctx, updateRegistration,
		arg.Status,
		arg.CertPem,
		arg.ClientID,
		arg.ID,
	)
	var i Registration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CsrPem,
		&i.CertPem,
		&i.ClientID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RemoteAddr,
	)
	return i, err
}
