// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, revision, display_name, arch_package_name, vendor_name, source_identity, icon_artifact_id, icon_sha256, history_json, created_at, modified_at, repo_publish, repo_pkgname_override, repo_published_pkgname, auto_build_policy, compile_cache_policy FROM projects WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DisplayName,
		&i.ArchPackageName,
		&i.VendorName,
		&i.SourceIdentity,
		&i.IconArtifactID,
		&i.IconSha256,
		&i.HistoryJson,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RepoPublish,
		&i.RepoPkgnameOverride,
		&i.RepoPublishedPkgname,
		&i.AutoBuildPolicy,
		&i.CompileCachePolicy,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (
    id, revision, display_name, arch_package_name, vendor_name, source_identity,
    icon_artifact_id, icon_sha256, history_json, created_at, modified_at
) VALUES (?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, revision, display_name, arch_package_name, vendor_name, source_identity, icon_artifact_id, icon_sha256, history_json, created_at, modified_at, repo_publish, repo_pkgname_override, repo_published_pkgname, auto_build_policy, compile_cache_policy
`

type InsertProjectParams struct {
	ID              string         `json:"id"`
	DisplayName     string         `json:"display_name"`
	ArchPackageName string         `json:"arch_package_name"`
	VendorName      string         `json:"vendor_name"`
	SourceIdentity  string         `json:"source_identity"`
	IconArtifactID  sql.NullString `json:"icon_artifact_id"`
	IconSha256      string         `json:"icon_sha256"`
	HistoryJson     string         `json:"history_json"`
	CreatedAt       string         `json:"created_at"`
	ModifiedAt      string         `json:"modified_at"`
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, insertProject,
		arg.ID,
		arg.DisplayName,
		arg.ArchPackageName,
		arg.VendorName,
		arg.SourceIdentity,
		arg.IconArtifactID,
		arg.IconSha256,
		arg.HistoryJson,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DisplayName,
		&i.ArchPackageName,
		&i.VendorName,
		&i.SourceIdentity,
		&i.IconArtifactID,
		&i.IconSha256,
		&i.HistoryJson,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RepoPublish,
		&i.RepoPkgnameOverride,
		&i.RepoPublishedPkgname,
		&i.AutoBuildPolicy,
		&i.CompileCachePolicy,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, revision, display_name, arch_package_name, vendor_name, source_identity, icon_artifact_id, icon_sha256, history_json, created_at, modified_at, repo_publish, repo_pkgname_override, repo_published_pkgname, auto_build_policy, compile_cache_policy FROM projects ORDER BY display_name COLLATE NOCASE, id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.DisplayName,
			&i.ArchPackageName,
			&i.VendorName,
			&i.SourceIdentity,
			&i.IconArtifactID,
			&i.IconSha256,
			&i.HistoryJson,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RepoPublish,
			&i.RepoPkgnameOverride,
			&i.RepoPublishedPkgname,
			&i.AutoBuildPolicy,
			&i.CompileCachePolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsBySourceIdentity = `-- name: ListProjectsBySourceIdentity :many
SELECT id, revision, display_name, arch_package_name, vendor_name, source_identity, icon_artifact_id, icon_sha256, history_json, created_at, modified_at, repo_publish, repo_pkgname_override, repo_published_pkgname, auto_build_policy, compile_cache_policy FROM projects WHERE source_identity = ?
`

func (q *Queries) ListProjectsBySourceIdentity(ctx context.Context, sourceIdentity string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjectsBySourceIdentity, sourceIdentity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Revision,
			&i.DisplayName,
			&i.ArchPackageName,
			&i.VendorName,
			&i.SourceIdentity,
			&i.IconArtifactID,
			&i.IconSha256,
			&i.HistoryJson,
			&i.CreatedAt,
			&i.ModifiedAt,
			&i.RepoPublish,
			&i.RepoPkgnameOverride,
			&i.RepoPublishedPkgname,
			&i.AutoBuildPolicy,
			&i.CompileCachePolicy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET display_name = ?,
    arch_package_name = ?,
    vendor_name = ?,
    source_identity = ?,
    icon_artifact_id = ?,
    icon_sha256 = ?,
    history_json = ?,
    auto_build_policy = ?,
    compile_cache_policy = ?,
    modified_at = ?,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, revision, display_name, arch_package_name, vendor_name, source_identity, icon_artifact_id, icon_sha256, history_json, created_at, modified_at, repo_publish, repo_pkgname_override, repo_published_pkgname, auto_build_policy, compile_cache_policy
`

type UpdateProjectParams struct {
	DisplayName        string         `json:"display_name"`
	ArchPackageName    string         `json:"arch_package_name"`
	VendorName         string         `json:"vendor_name"`
	SourceIdentity     string         `json:"source_identity"`
	IconArtifactID     sql.NullString `json:"icon_artifact_id"`
	IconSha256         string         `json:"icon_sha256"`
	HistoryJson        string         `json:"history_json"`
	AutoBuildPolicy    string         `json:"auto_build_policy"`
	CompileCachePolicy string         `json:"compile_cache_policy"`
	ModifiedAt         string         `json:"modified_at"`
	ID                 string         `json:"id"`
	Revision           int64          `json:"revision"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProject,
		arg.DisplayName,
		arg.ArchPackageName,
		arg.VendorName,
		arg.SourceIdentity,
		arg.IconArtifactID,
		arg.IconSha256,
		arg.HistoryJson,
		arg.AutoBuildPolicy,
		arg.CompileCachePolicy,
		arg.ModifiedAt,
		arg.ID,
		arg.Revision,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DisplayName,
		&i.ArchPackageName,
		&i.VendorName,
		&i.SourceIdentity,
		&i.IconArtifactID,
		&i.IconSha256,
		&i.HistoryJson,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RepoPublish,
		&i.RepoPkgnameOverride,
		&i.RepoPublishedPkgname,
		&i.AutoBuildPolicy,
		&i.CompileCachePolicy,
	)
	return i, err
}
