// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: releases.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const deleteRelease = `-- name: DeleteRelease :exec
DELETE FROM releases WHERE id = ?
`

func (q *Queries) DeleteRelease(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRelease, id)
	return err
}

const deleteReleaseArtifactsByRole = `-- name: DeleteReleaseArtifactsByRole :exec
DELETE FROM release_artifacts WHERE release_id = ? AND role = ?
`

type DeleteReleaseArtifactsByRoleParams struct {
	ReleaseID string `json:"release_id"`
	Role      string `json:"role"`
}

func (q *Queries) DeleteReleaseArtifactsByRole(ctx context.Context, arg DeleteReleaseArtifactsByRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteReleaseArtifactsByRole, arg.ReleaseID, arg.Role)
	return err
}

const getRelease = `-- name: GetRelease :one
SELECT id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at FROM releases WHERE id = ?
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.State,
		&i.SourceType,
		&i.VendorVersion,
		&i.OriginalFilename,
		&i.SourceSha256,
		&i.SourceArtifactID,
		&i.ArchPackageName,
		&i.ArchPkgrel,
		&i.BodyJson,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getReleaseByProjectSHA256 = `-- name: GetReleaseByProjectSHA256 :one
SELECT id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at FROM releases WHERE project_id = ? AND source_sha256 = ?
`

type GetReleaseByProjectSHA256Params struct {
	ProjectID    string `json:"project_id"`
	SourceSha256 string `json:"source_sha256"`
}

func (q *Queries) GetReleaseByProjectSHA256(ctx context.Context, arg GetReleaseByProjectSHA256Params) (Release, error) {
	row := q.db.QueryRowContext(ctx, getReleaseByProjectSHA256, arg.ProjectID, arg.SourceSha256)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.State,
		&i.SourceType,
		&i.VendorVersion,
		&i.OriginalFilename,
		&i.SourceSha256,
		&i.SourceArtifactID,
		&i.ArchPackageName,
		&i.ArchPkgrel,
		&i.BodyJson,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getUpdateCheckState = `-- name: GetUpdateCheckState :one
SELECT update_source_id, last_checked_at, last_message, last_error, detected_version, detected_filename, detected_sha256, detected_url, etag, signature_verified, job_id FROM update_check_state WHERE update_source_id = ?
`

func (q *Queries) GetUpdateCheckState(ctx context.Context, updateSourceID string) (UpdateCheckState, error) {
	row := q.db.QueryRowContext(ctx, getUpdateCheckState, updateSourceID)
	var i UpdateCheckState
	err := row.Scan(
		&i.UpdateSourceID,
		&i.LastCheckedAt,
		&i.LastMessage,
		&i.LastError,
		&i.DetectedVersion,
		&i.DetectedFilename,
		&i.DetectedSha256,
		&i.DetectedUrl,
		&i.Etag,
		&i.SignatureVerified,
		&i.JobID,
	)
	return i, err
}

const getUpdateSourceByRelease = `-- name: GetUpdateSourceByRelease :one
SELECT id, release_id, revision, strategy, config_json FROM update_sources WHERE release_id = ?
`

func (q *Queries) GetUpdateSourceByRelease(ctx context.Context, releaseID string) (UpdateSource, error) {
	row := q.db.QueryRowContext(ctx, getUpdateSourceByRelease, releaseID)
	var i UpdateSource
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Revision,
		&i.Strategy,
		&i.ConfigJson,
	)
	return i, err
}

const insertBuild = `-- name: InsertBuild :one
INSERT INTO builds (id, release_id, status, log_text, started_at, finished_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, release_id, status, log_text, started_at, finished_at
`

type InsertBuildParams struct {
	ID         string         `json:"id"`
	ReleaseID  string         `json:"release_id"`
	Status     string         `json:"status"`
	LogText    string         `json:"log_text"`
	StartedAt  sql.NullString `json:"started_at"`
	FinishedAt sql.NullString `json:"finished_at"`
}

func (q *Queries) InsertBuild(ctx context.Context, arg InsertBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, insertBuild,
		arg.ID,
		arg.ReleaseID,
		arg.Status,
		arg.LogText,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Status,
		&i.LogText,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertBuildArtifact = `-- name: InsertBuildArtifact :exec
INSERT OR IGNORE INTO build_artifacts (build_id, artifact_id)
VALUES (?, ?)
`

type InsertBuildArtifactParams struct {
	BuildID    string `json:"build_id"`
	ArtifactID string `json:"artifact_id"`
}

func (q *Queries) InsertBuildArtifact(ctx context.Context, arg InsertBuildArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertBuildArtifact, arg.BuildID, arg.ArtifactID)
	return err
}

const insertRelease = `-- name: InsertRelease :one
INSERT INTO releases (
    id, project_id, revision, state, source_type, vendor_version, original_filename,
    source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json,
    created_at, modified_at
) VALUES (?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at
`

type InsertReleaseParams struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	State            string         `json:"state"`
	SourceType       string         `json:"source_type"`
	VendorVersion    string         `json:"vendor_version"`
	OriginalFilename string         `json:"original_filename"`
	SourceSha256     string         `json:"source_sha256"`
	SourceArtifactID sql.NullString `json:"source_artifact_id"`
	ArchPackageName  string         `json:"arch_package_name"`
	ArchPkgrel       int64          `json:"arch_pkgrel"`
	BodyJson         string         `json:"body_json"`
	CreatedAt        string         `json:"created_at"`
	ModifiedAt       string         `json:"modified_at"`
}

func (q *Queries) InsertRelease(ctx context.Context, arg InsertReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, insertRelease,
		arg.ID,
		arg.ProjectID,
		arg.State,
		arg.SourceType,
		arg.VendorVersion,
		arg.OriginalFilename,
		arg.SourceSha256,
		arg.SourceArtifactID,
		arg.ArchPackageName,
		arg.ArchPkgrel,
		arg.BodyJson,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.State,
		&i.SourceType,
		&i.VendorVersion,
		&i.OriginalFilename,
		&i.SourceSha256,
		&i.SourceArtifactID,
		&i.ArchPackageName,
		&i.ArchPkgrel,
		&i.BodyJson,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const insertReleaseArtifact = `-- name: InsertReleaseArtifact :exec
INSERT OR IGNORE INTO release_artifacts (release_id, artifact_id, role)
VALUES (?, ?, ?)
`

type InsertReleaseArtifactParams struct {
	ReleaseID  string `json:"release_id"`
	ArtifactID string `json:"artifact_id"`
	Role       string `json:"role"`
}

func (q *Queries) InsertReleaseArtifact(ctx context.Context, arg InsertReleaseArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertReleaseArtifact, arg.ReleaseID, arg.ArtifactID, arg.Role)
	return err
}

const insertUpdateSource = `-- name: InsertUpdateSource :one
INSERT INTO update_sources (id, release_id, revision, strategy, config_json)
VALUES (?, ?, 1, ?, ?)
RETURNING id, release_id, revision, strategy, config_json
`

type InsertUpdateSourceParams struct {
	ID         string `json:"id"`
	ReleaseID  string `json:"release_id"`
	Strategy   string `json:"strategy"`
	ConfigJson string `json:"config_json"`
}

func (q *Queries) InsertUpdateSource(ctx context.Context, arg InsertUpdateSourceParams) (UpdateSource, error) {
	row := q.db.QueryRowContext(ctx, insertUpdateSource,
		arg.ID,
		arg.ReleaseID,
		arg.Strategy,
		arg.ConfigJson,
	)
	var i UpdateSource
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Revision,
		&i.Strategy,
		&i.ConfigJson,
	)
	return i, err
}

const listBuildArtifactsForBuild = `-- name: ListBuildArtifactsForBuild :many
SELECT artifacts.id, artifacts.sha256, artifacts.size_bytes, artifacts.original_filename, artifacts.kind, artifacts.created_at
FROM build_artifacts
JOIN artifacts ON artifacts.id = build_artifacts.artifact_id
WHERE build_artifacts.build_id = ?
ORDER BY artifacts.created_at, artifacts.id
`

func (q *Queries) ListBuildArtifactsForBuild(ctx context.Context, buildID string) ([]Artifact, error) {
	rows, err := q.db.QueryContext(ctx, listBuildArtifactsForBuild, buildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artifact
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.SizeBytes,
			&i.OriginalFilename,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBuildsForRelease = `-- name: ListBuildsForRelease :many
SELECT id, release_id, status, log_text, started_at, finished_at FROM builds WHERE release_id = ? ORDER BY started_at
`

func (q *Queries) ListBuildsForRelease(ctx context.Context, releaseID string) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, listBuildsForRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Status,
			&i.LogText,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseArtifacts = `-- name: ListReleaseArtifacts :many
SELECT artifact_id, role FROM release_artifacts WHERE release_id = ?
`

type ListReleaseArtifactsRow struct {
	ArtifactID string `json:"artifact_id"`
	Role       string `json:"role"`
}

func (q *Queries) ListReleaseArtifacts(ctx context.Context, releaseID string) ([]ListReleaseArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseArtifacts, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleaseArtifactsRow
	for rows.Next() {
		var i ListReleaseArtifactsRow
		if err := rows.Scan(&i.ArtifactID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleaseIconArtifacts = `-- name: ListReleaseIconArtifacts :many
SELECT release_id, artifact_id FROM release_artifacts WHERE role = 'icon'
`

type ListReleaseIconArtifactsRow struct {
	ReleaseID  string `json:"release_id"`
	ArtifactID string `json:"artifact_id"`
}

func (q *Queries) ListReleaseIconArtifacts(ctx context.Context) ([]ListReleaseIconArtifactsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReleaseIconArtifacts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleaseIconArtifactsRow
	for rows.Next() {
		var i ListReleaseIconArtifactsRow
		if err := rows.Scan(&i.ReleaseID, &i.ArtifactID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReleasesForProject = `-- name: ListReleasesForProject :many
SELECT id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at FROM releases WHERE project_id = ? ORDER BY created_at
`

func (q *Queries) ListReleasesForProject(ctx context.Context, projectID string) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleasesForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Revision,
			&i.State,
			&i.SourceType,
			&i.VendorVersion,
			&i.OriginalFilename,
			&i.SourceSha256,
			&i.SourceArtifactID,
			&i.ArchPackageName,
			&i.ArchPkgrel,
			&i.BodyJson,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparingReleases = `-- name: ListPreparingReleases :many
SELECT id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at FROM releases WHERE state = 'preparing' ORDER BY created_at
`

func (q *Queries) ListPreparingReleases(ctx context.Context) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listPreparingReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Revision,
			&i.State,
			&i.SourceType,
			&i.VendorVersion,
			&i.OriginalFilename,
			&i.SourceSha256,
			&i.SourceArtifactID,
			&i.ArchPackageName,
			&i.ArchPkgrel,
			&i.BodyJson,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpdateSources = `-- name: ListUpdateSources :many
SELECT id, release_id, revision, strategy, config_json FROM update_sources
`

func (q *Queries) ListUpdateSources(ctx context.Context) ([]UpdateSource, error) {
	rows, err := q.db.QueryContext(ctx, listUpdateSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateSource
	for rows.Next() {
		var i UpdateSource
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Revision,
			&i.Strategy,
			&i.ConfigJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases
SET state = ?,
    source_type = ?,
    vendor_version = ?,
    original_filename = ?,
    source_sha256 = ?,
    source_artifact_id = ?,
    arch_package_name = ?,
    arch_pkgrel = ?,
    body_json = ?,
    modified_at = ?,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at
`

type UpdateReleaseParams struct {
	State            string         `json:"state"`
	SourceType       string         `json:"source_type"`
	VendorVersion    string         `json:"vendor_version"`
	OriginalFilename string         `json:"original_filename"`
	SourceSha256     string         `json:"source_sha256"`
	SourceArtifactID sql.NullString `json:"source_artifact_id"`
	ArchPackageName  string         `json:"arch_package_name"`
	ArchPkgrel       int64          `json:"arch_pkgrel"`
	BodyJson         string         `json:"body_json"`
	ModifiedAt       string         `json:"modified_at"`
	ID               string         `json:"id"`
	Revision         int64          `json:"revision"`
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateRelease,
		arg.State,
		arg.SourceType,
		arg.VendorVersion,
		arg.OriginalFilename,
		arg.SourceSha256,
		arg.SourceArtifactID,
		arg.ArchPackageName,
		arg.ArchPkgrel,
		arg.BodyJson,
		arg.ModifiedAt,
		arg.ID,
		arg.Revision,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.State,
		&i.SourceType,
		&i.VendorVersion,
		&i.OriginalFilename,
		&i.SourceSha256,
		&i.SourceArtifactID,
		&i.ArchPackageName,
		&i.ArchPkgrel,
		&i.BodyJson,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateUpdateSource = `-- name: UpdateUpdateSource :one
UPDATE update_sources
SET strategy = ?,
    config_json = ?,
    revision = revision + 1
WHERE release_id = ? AND revision = ?
RETURNING id, release_id, revision, strategy, config_json
`

type UpdateUpdateSourceParams struct {
	Strategy   string `json:"strategy"`
	ConfigJson string `json:"config_json"`
	ReleaseID  string `json:"release_id"`
	Revision   int64  `json:"revision"`
}

func (q *Queries) UpdateUpdateSource(ctx context.Context, arg UpdateUpdateSourceParams) (UpdateSource, error) {
	row := q.db.QueryRowContext(ctx, updateUpdateSource,
		arg.Strategy,
		arg.ConfigJson,
		arg.ReleaseID,
		arg.Revision,
	)
	var i UpdateSource
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Revision,
		&i.Strategy,
		&i.ConfigJson,
	)
	return i, err
}

const upsertUpdateCheckState = `-- name: UpsertUpdateCheckState :exec
INSERT INTO update_check_state (
    update_source_id, last_checked_at, last_message, last_error, detected_version,
    detected_filename, detected_sha256, detected_url, etag, signature_verified, job_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (update_source_id) DO UPDATE SET
    last_checked_at = excluded.last_checked_at,
    last_message = excluded.last_message,
    last_error = excluded.last_error,
    detected_version = excluded.detected_version,
    detected_filename = excluded.detected_filename,
    detected_sha256 = excluded.detected_sha256,
    detected_url = excluded.detected_url,
    etag = excluded.etag,
    signature_verified = excluded.signature_verified,
    job_id = excluded.job_id
`

type UpsertUpdateCheckStateParams struct {
	UpdateSourceID    string `json:"update_source_id"`
	LastCheckedAt     string `json:"last_checked_at"`
	LastMessage       string `json:"last_message"`
	LastError         string `json:"last_error"`
	DetectedVersion   string `json:"detected_version"`
	DetectedFilename  string `json:"detected_filename"`
	DetectedSha256    string `json:"detected_sha256"`
	DetectedUrl       string `json:"detected_url"`
	Etag              string `json:"etag"`
	SignatureVerified int64  `json:"signature_verified"`
	JobID             string `json:"job_id"`
}

func (q *Queries) UpsertUpdateCheckState(ctx context.Context, arg UpsertUpdateCheckStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertUpdateCheckState,
		arg.UpdateSourceID,
		arg.LastCheckedAt,
		arg.LastMessage,
		arg.LastError,
		arg.DetectedVersion,
		arg.DetectedFilename,
		arg.DetectedSha256,
		arg.DetectedUrl,
		arg.Etag,
		arg.SignatureVerified,
		arg.JobID,
	)
	return err
}
