// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const deleteAllChannelEntries = `-- name: DeleteAllChannelEntries :exec
DELETE FROM repo_channel_entries
`

func (q *Queries) DeleteAllChannelEntries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllChannelEntries)
	return err
}

const deleteAllRepoDatabases = `-- name: DeleteAllRepoDatabases :exec
DELETE FROM repo_databases
`

func (q *Queries) DeleteAllRepoDatabases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllRepoDatabases)
	return err
}

const deleteAllSoaks = `-- name: DeleteAllSoaks :exec
DELETE FROM repo_soaks
`

func (q *Queries) DeleteAllSoaks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllSoaks)
	return err
}

const deleteChannelEntriesForProject = `-- name: DeleteChannelEntriesForProject :exec
DELETE FROM repo_channel_entries WHERE project_id = ?
`

func (q *Queries) DeleteChannelEntriesForProject(ctx context.Context, projectID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteChannelEntriesForProject, projectID)
	return err
}

const deleteChannelEntry = `-- name: DeleteChannelEntry :exec
DELETE FROM repo_channel_entries WHERE channel = ? AND arch = ? AND pkgname = ?
`

type DeleteChannelEntryParams struct {
	Channel string `json:"channel"`
	Arch    string `json:"arch"`
	Pkgname string `json:"pkgname"`
}

func (q *Queries) DeleteChannelEntry(ctx context.Context, arg DeleteChannelEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelEntry, arg.Channel, arg.Arch, arg.Pkgname)
	return err
}

const deleteRepoDatabase = `-- name: DeleteRepoDatabase :exec
DELETE FROM repo_databases WHERE channel = ? AND arch = ?
`

type DeleteRepoDatabaseParams struct {
	Channel string `json:"channel"`
	Arch    string `json:"arch"`
}

func (q *Queries) DeleteRepoDatabase(ctx context.Context, arg DeleteRepoDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, deleteRepoDatabase, arg.Channel, arg.Arch)
	return err
}

const deleteRepoPackageByName = `-- name: DeleteRepoPackageByName :exec
DELETE FROM repo_packages WHERE pkgname = ?
`

func (q *Queries) DeleteRepoPackageByName(ctx context.Context, pkgname string) error {
	_, err := q.db.ExecContext(ctx, deleteRepoPackageByName, pkgname)
	return err
}

const deleteRepoPackageByProject = `-- name: DeleteRepoPackageByProject :exec
DELETE FROM repo_packages WHERE project_id = ?
`

func (q *Queries) DeleteRepoPackageByProject(ctx context.Context, projectID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteRepoPackageByProject, projectID)
	return err
}

const deleteSoaksForProject = `-- name: DeleteSoaksForProject :exec
DELETE FROM repo_soaks WHERE project_id = ?
`

func (q *Queries) DeleteSoaksForProject(ctx context.Context, projectID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteSoaksForProject, projectID)
	return err
}

const deleteStableChannelEntriesForProject = `-- name: DeleteStableChannelEntriesForProject :exec
DELETE FROM repo_channel_entries WHERE project_id = ? AND channel = 'stable'
`

func (q *Queries) DeleteStableChannelEntriesForProject(ctx context.Context, projectID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteStableChannelEntriesForProject, projectID)
	return err
}

const deleteStableProjectChannelEntries = `-- name: DeleteStableProjectChannelEntries :exec
DELETE FROM repo_channel_entries WHERE channel = 'stable' AND project_id IS NOT NULL
`

func (q *Queries) DeleteStableProjectChannelEntries(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStableProjectChannelEntries)
	return err
}

const deleteStableRepoDatabases = `-- name: DeleteStableRepoDatabases :exec
DELETE FROM repo_databases WHERE channel = 'stable'
`

func (q *Queries) DeleteStableRepoDatabases(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteStableRepoDatabases)
	return err
}

const getChannelEntry = `-- name: GetChannelEntry :one
SELECT channel, arch, pkgname, project_id, release_id, epoch, pkgver, pkgrel, artifact_id, sig_artifact_id, filename, published_at FROM repo_channel_entries
WHERE channel = ? AND arch = ? AND pkgname = ?
`

type GetChannelEntryParams struct {
	Channel string `json:"channel"`
	Arch    string `json:"arch"`
	Pkgname string `json:"pkgname"`
}

func (q *Queries) GetChannelEntry(ctx context.Context, arg GetChannelEntryParams) (RepoChannelEntry, error) {
	row := q.db.QueryRowContext(ctx, getChannelEntry, arg.Channel, arg.Arch, arg.Pkgname)
	var i RepoChannelEntry
	err := row.Scan(
		&i.Channel,
		&i.Arch,
		&i.Pkgname,
		&i.ProjectID,
		&i.ReleaseID,
		&i.Epoch,
		&i.Pkgver,
		&i.Pkgrel,
		&i.ArtifactID,
		&i.SigArtifactID,
		&i.Filename,
		&i.PublishedAt,
	)
	return i, err
}

const getProjectRepoPolicy = `-- name: GetProjectRepoPolicy :one
SELECT automatic_soak, soak_seconds_override
FROM project_repo_policies
WHERE project_id = ?
`

type GetProjectRepoPolicyRow struct {
	AutomaticSoak       int64 `json:"automatic_soak"`
	SoakSecondsOverride int64 `json:"soak_seconds_override"`
}

func (q *Queries) GetProjectRepoPolicy(ctx context.Context, projectID string) (GetProjectRepoPolicyRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectRepoPolicy, projectID)
	var i GetProjectRepoPolicyRow
	err := row.Scan(&i.AutomaticSoak, &i.SoakSecondsOverride)
	return i, err
}

const getRepoDatabase = `-- name: GetRepoDatabase :one
SELECT channel, arch, db_artifact_id, db_sig_artifact_id, files_artifact_id, files_sig_artifact_id, generated_at FROM repo_databases WHERE channel = ? AND arch = ?
`

type GetRepoDatabaseParams struct {
	Channel string `json:"channel"`
	Arch    string `json:"arch"`
}

func (q *Queries) GetRepoDatabase(ctx context.Context, arg GetRepoDatabaseParams) (RepoDatabase, error) {
	row := q.db.QueryRowContext(ctx, getRepoDatabase, arg.Channel, arg.Arch)
	var i RepoDatabase
	err := row.Scan(
		&i.Channel,
		&i.Arch,
		&i.DbArtifactID,
		&i.DbSigArtifactID,
		&i.FilesArtifactID,
		&i.FilesSigArtifactID,
		&i.GeneratedAt,
	)
	return i, err
}

const getRepoPackageByName = `-- name: GetRepoPackageByName :one
SELECT pkgname, project_id, original_pkgname, internal, created_at FROM repo_packages WHERE pkgname = ?
`

func (q *Queries) GetRepoPackageByName(ctx context.Context, pkgname string) (RepoPackage, error) {
	row := q.db.QueryRowContext(ctx, getRepoPackageByName, pkgname)
	var i RepoPackage
	err := row.Scan(
		&i.Pkgname,
		&i.ProjectID,
		&i.OriginalPkgname,
		&i.Internal,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoPackageByProject = `-- name: GetRepoPackageByProject :one
SELECT pkgname, project_id, original_pkgname, internal, created_at FROM repo_packages WHERE project_id = ?
`

func (q *Queries) GetRepoPackageByProject(ctx context.Context, projectID sql.NullString) (RepoPackage, error) {
	row := q.db.QueryRowContext(ctx, getRepoPackageByProject, projectID)
	var i RepoPackage
	err := row.Scan(
		&i.Pkgname,
		&i.ProjectID,
		&i.OriginalPkgname,
		&i.Internal,
		&i.CreatedAt,
	)
	return i, err
}

const getRepoSettings = `-- name: GetRepoSettings :one
SELECT id, revision, enabled, listen_hosts, listen_port, advertised_url, stable_enabled, soak_seconds, package_name_prefix, trust_mode, signing_fingerprint, signing_initialized, signing_pubkey_artifact_id, root_pubkey_artifact_id, root_fingerprint, certified_pubkey_artifact_id, keyring_gpg_artifact_id, keyring_trusted_artifact_id, keyring_revoked_artifact_id, keyring_package_artifact_id, keyring_package_sig_artifact_id, keyring_version, recovery_message, modified_at FROM repo_settings WHERE id = 1
`

func (q *Queries) GetRepoSettings(ctx context.Context) (RepoSetting, error) {
	row := q.db.QueryRowContext(ctx, getRepoSettings)
	var i RepoSetting
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Enabled,
		&i.ListenHosts,
		&i.ListenPort,
		&i.AdvertisedUrl,
		&i.StableEnabled,
		&i.SoakSeconds,
		&i.PackageNamePrefix,
		&i.TrustMode,
		&i.SigningFingerprint,
		&i.SigningInitialized,
		&i.SigningPubkeyArtifactID,
		&i.RootPubkeyArtifactID,
		&i.RootFingerprint,
		&i.CertifiedPubkeyArtifactID,
		&i.KeyringGpgArtifactID,
		&i.KeyringTrustedArtifactID,
		&i.KeyringRevokedArtifactID,
		&i.KeyringPackageArtifactID,
		&i.KeyringPackageSigArtifactID,
		&i.KeyringVersion,
		&i.RecoveryMessage,
		&i.ModifiedAt,
	)
	return i, err
}

const getSoak = `-- name: GetSoak :one
SELECT pkgname, arch, pkgver, project_id, release_id, epoch, pkgrel, artifact_id, sig_artifact_id, soak_started_at, eligible_at, status FROM repo_soaks WHERE pkgname = ? AND arch = ? AND pkgver = ?
`

type GetSoakParams struct {
	Pkgname string `json:"pkgname"`
	Arch    string `json:"arch"`
	Pkgver  string `json:"pkgver"`
}

func (q *Queries) GetSoak(ctx context.Context, arg GetSoakParams) (RepoSoak, error) {
	row := q.db.QueryRowContext(ctx, getSoak, arg.Pkgname, arg.Arch, arg.Pkgver)
	var i RepoSoak
	err := row.Scan(
		&i.Pkgname,
		&i.Arch,
		&i.Pkgver,
		&i.ProjectID,
		&i.ReleaseID,
		&i.Epoch,
		&i.Pkgrel,
		&i.ArtifactID,
		&i.SigArtifactID,
		&i.SoakStartedAt,
		&i.EligibleAt,
		&i.Status,
	)
	return i, err
}

const insertRepoPackage = `-- name: InsertRepoPackage :one
INSERT INTO repo_packages (pkgname, project_id, original_pkgname, internal, created_at)
VALUES (?, ?, ?, ?, ?)
RETURNING pkgname, project_id, original_pkgname, internal, created_at
`

type InsertRepoPackageParams struct {
	Pkgname         string         `json:"pkgname"`
	ProjectID       sql.NullString `json:"project_id"`
	OriginalPkgname string         `json:"original_pkgname"`
	Internal        int64          `json:"internal"`
	CreatedAt       string         `json:"created_at"`
}

func (q *Queries) InsertRepoPackage(ctx context.Context, arg InsertRepoPackageParams) (RepoPackage, error) {
	row := q.db.QueryRowContext(ctx, insertRepoPackage,
		arg.Pkgname,
		arg.ProjectID,
		arg.OriginalPkgname,
		arg.Internal,
		arg.CreatedAt,
	)
	var i RepoPackage
	err := row.Scan(
		&i.Pkgname,
		&i.ProjectID,
		&i.OriginalPkgname,
		&i.Internal,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSoaks = `-- name: ListActiveSoaks :many
SELECT pkgname, arch, pkgver, project_id, release_id, epoch, pkgrel, artifact_id, sig_artifact_id, soak_started_at, eligible_at, status FROM repo_soaks WHERE status IN ('soaking', 'eligible') ORDER BY pkgname, arch, pkgver
`

func (q *Queries) ListActiveSoaks(ctx context.Context) ([]RepoSoak, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSoaks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSoak
	for rows.Next() {
		var i RepoSoak
		if err := rows.Scan(
			&i.Pkgname,
			&i.Arch,
			&i.Pkgver,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Epoch,
			&i.Pkgrel,
			&i.ArtifactID,
			&i.SigArtifactID,
			&i.SoakStartedAt,
			&i.EligibleAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelArches = `-- name: ListChannelArches :many
SELECT DISTINCT arch FROM repo_channel_entries ORDER BY arch
`

func (q *Queries) ListChannelArches(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listChannelArches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var arch string
		if err := rows.Scan(&arch); err != nil {
			return nil, err
		}
		items = append(items, arch)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelEntries = `-- name: ListChannelEntries :many
SELECT channel, arch, pkgname, project_id, release_id, epoch, pkgver, pkgrel, artifact_id, sig_artifact_id, filename, published_at FROM repo_channel_entries
ORDER BY channel, arch, pkgname
`

func (q *Queries) ListChannelEntries(ctx context.Context) ([]RepoChannelEntry, error) {
	rows, err := q.db.QueryContext(ctx, listChannelEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoChannelEntry
	for rows.Next() {
		var i RepoChannelEntry
		if err := rows.Scan(
			&i.Channel,
			&i.Arch,
			&i.Pkgname,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Epoch,
			&i.Pkgver,
			&i.Pkgrel,
			&i.ArtifactID,
			&i.SigArtifactID,
			&i.Filename,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelEntriesForChannelArch = `-- name: ListChannelEntriesForChannelArch :many
SELECT channel, arch, pkgname, project_id, release_id, epoch, pkgver, pkgrel, artifact_id, sig_artifact_id, filename, published_at FROM repo_channel_entries
WHERE channel = ? AND arch = ?
ORDER BY pkgname
`

type ListChannelEntriesForChannelArchParams struct {
	Channel string `json:"channel"`
	Arch    string `json:"arch"`
}

func (q *Queries) ListChannelEntriesForChannelArch(ctx context.Context, arg ListChannelEntriesForChannelArchParams) ([]RepoChannelEntry, error) {
	rows, err := q.db.QueryContext(ctx, listChannelEntriesForChannelArch, arg.Channel, arg.Arch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoChannelEntry
	for rows.Next() {
		var i RepoChannelEntry
		if err := rows.Scan(
			&i.Channel,
			&i.Arch,
			&i.Pkgname,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Epoch,
			&i.Pkgver,
			&i.Pkgrel,
			&i.ArtifactID,
			&i.SigArtifactID,
			&i.Filename,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoDatabases = `-- name: ListRepoDatabases :many
SELECT channel, arch, db_artifact_id, db_sig_artifact_id, files_artifact_id, files_sig_artifact_id, generated_at FROM repo_databases ORDER BY channel, arch
`

func (q *Queries) ListRepoDatabases(ctx context.Context) ([]RepoDatabase, error) {
	rows, err := q.db.QueryContext(ctx, listRepoDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoDatabase
	for rows.Next() {
		var i RepoDatabase
		if err := rows.Scan(
			&i.Channel,
			&i.Arch,
			&i.DbArtifactID,
			&i.DbSigArtifactID,
			&i.FilesArtifactID,
			&i.FilesSigArtifactID,
			&i.GeneratedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoPackages = `-- name: ListRepoPackages :many
SELECT pkgname, project_id, original_pkgname, internal, created_at FROM repo_packages ORDER BY pkgname
`

func (q *Queries) ListRepoPackages(ctx context.Context) ([]RepoPackage, error) {
	rows, err := q.db.QueryContext(ctx, listRepoPackages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoPackage
	for rows.Next() {
		var i RepoPackage
		if err := rows.Scan(
			&i.Pkgname,
			&i.ProjectID,
			&i.OriginalPkgname,
			&i.Internal,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoaks = `-- name: ListSoaks :many
SELECT pkgname, arch, pkgver, project_id, release_id, epoch, pkgrel, artifact_id, sig_artifact_id, soak_started_at, eligible_at, status FROM repo_soaks ORDER BY pkgname, arch, pkgver
`

func (q *Queries) ListSoaks(ctx context.Context) ([]RepoSoak, error) {
	rows, err := q.db.QueryContext(ctx, listSoaks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSoak
	for rows.Next() {
		var i RepoSoak
		if err := rows.Scan(
			&i.Pkgname,
			&i.Arch,
			&i.Pkgver,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Epoch,
			&i.Pkgrel,
			&i.ArtifactID,
			&i.SigArtifactID,
			&i.SoakStartedAt,
			&i.EligibleAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSoaksForPackage = `-- name: ListSoaksForPackage :many
SELECT pkgname, arch, pkgver, project_id, release_id, epoch, pkgrel, artifact_id, sig_artifact_id, soak_started_at, eligible_at, status FROM repo_soaks WHERE pkgname = ? AND arch = ? ORDER BY pkgver
`

type ListSoaksForPackageParams struct {
	Pkgname string `json:"pkgname"`
	Arch    string `json:"arch"`
}

func (q *Queries) ListSoaksForPackage(ctx context.Context, arg ListSoaksForPackageParams) ([]RepoSoak, error) {
	rows, err := q.db.QueryContext(ctx, listSoaksForPackage, arg.Pkgname, arg.Arch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSoak
	for rows.Next() {
		var i RepoSoak
		if err := rows.Scan(
			&i.Pkgname,
			&i.Arch,
			&i.Pkgver,
			&i.ProjectID,
			&i.ReleaseID,
			&i.Epoch,
			&i.Pkgrel,
			&i.ArtifactID,
			&i.SigArtifactID,
			&i.SoakStartedAt,
			&i.EligibleAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetRepoAfterSigningKeyLoss = `-- name: ResetRepoAfterSigningKeyLoss :one
UPDATE repo_settings
SET revision = revision + 1,
    enabled = 0,
    trust_mode = 'direct',
    signing_fingerprint = '',
    signing_initialized = 0,
    signing_pubkey_artifact_id = NULL,
    root_pubkey_artifact_id = NULL,
    root_fingerprint = '',
    certified_pubkey_artifact_id = NULL,
    keyring_gpg_artifact_id = NULL,
    keyring_trusted_artifact_id = NULL,
    keyring_revoked_artifact_id = NULL,
    keyring_package_artifact_id = NULL,
    keyring_package_sig_artifact_id = NULL,
    keyring_version = 0,
    recovery_message = ?,
    modified_at = ?
WHERE id = 1
RETURNING id, revision, enabled, listen_hosts, listen_port, advertised_url, stable_enabled, soak_seconds, package_name_prefix, trust_mode, signing_fingerprint, signing_initialized, signing_pubkey_artifact_id, root_pubkey_artifact_id, root_fingerprint, certified_pubkey_artifact_id, keyring_gpg_artifact_id, keyring_trusted_artifact_id, keyring_revoked_artifact_id, keyring_package_artifact_id, keyring_package_sig_artifact_id, keyring_version, recovery_message, modified_at
`

type ResetRepoAfterSigningKeyLossParams struct {
	RecoveryMessage string `json:"recovery_message"`
	ModifiedAt      string `json:"modified_at"`
}

func (q *Queries) ResetRepoAfterSigningKeyLoss(ctx context.Context, arg ResetRepoAfterSigningKeyLossParams) (RepoSetting, error) {
	row := q.db.QueryRowContext(ctx, resetRepoAfterSigningKeyLoss, arg.RecoveryMessage, arg.ModifiedAt)
	var i RepoSetting
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Enabled,
		&i.ListenHosts,
		&i.ListenPort,
		&i.AdvertisedUrl,
		&i.StableEnabled,
		&i.SoakSeconds,
		&i.PackageNamePrefix,
		&i.TrustMode,
		&i.SigningFingerprint,
		&i.SigningInitialized,
		&i.SigningPubkeyArtifactID,
		&i.RootPubkeyArtifactID,
		&i.RootFingerprint,
		&i.CertifiedPubkeyArtifactID,
		&i.KeyringGpgArtifactID,
		&i.KeyringTrustedArtifactID,
		&i.KeyringRevokedArtifactID,
		&i.KeyringPackageArtifactID,
		&i.KeyringPackageSigArtifactID,
		&i.KeyringVersion,
		&i.RecoveryMessage,
		&i.ModifiedAt,
	)
	return i, err
}

const updateProjectRepo = `-- name: UpdateProjectRepo :one
UPDATE projects
SET repo_publish = ?,
    repo_pkgname_override = ?,
    repo_published_pkgname = ?,
    modified_at = ?,
    revision = revision + 1
WHERE id = ? AND revision = ?
RETURNING id, revision, display_name, arch_package_name, vendor_name, source_identity, icon_artifact_id, icon_sha256, history_json, created_at, modified_at, repo_publish, repo_pkgname_override, repo_published_pkgname, auto_build_policy, compile_cache_policy
`

type UpdateProjectRepoParams struct {
	RepoPublish          int64  `json:"repo_publish"`
	RepoPkgnameOverride  string `json:"repo_pkgname_override"`
	RepoPublishedPkgname string `json:"repo_published_pkgname"`
	ModifiedAt           string `json:"modified_at"`
	ID                   string `json:"id"`
	Revision             int64  `json:"revision"`
}

func (q *Queries) UpdateProjectRepo(ctx context.Context, arg UpdateProjectRepoParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, updateProjectRepo,
		arg.RepoPublish,
		arg.RepoPkgnameOverride,
		arg.RepoPublishedPkgname,
		arg.ModifiedAt,
		arg.ID,
		arg.Revision,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.DisplayName,
		&i.ArchPackageName,
		&i.VendorName,
		&i.SourceIdentity,
		&i.IconArtifactID,
		&i.IconSha256,
		&i.HistoryJson,
		&i.CreatedAt,
		&i.ModifiedAt,
		&i.RepoPublish,
		&i.RepoPkgnameOverride,
		&i.RepoPublishedPkgname,
		&i.AutoBuildPolicy,
		&i.CompileCachePolicy,
	)
	return i, err
}

const updateReleasePkgrel = `-- name: UpdateReleasePkgrel :one
UPDATE releases
SET arch_pkgrel = ?,
    body_json = ?,
    modified_at = ?,
    revision = revision + 1
WHERE id = ?
RETURNING id, project_id, revision, state, source_type, vendor_version, original_filename, source_sha256, source_artifact_id, arch_package_name, arch_pkgrel, body_json, created_at, modified_at
`

type UpdateReleasePkgrelParams struct {
	ArchPkgrel int64  `json:"arch_pkgrel"`
	BodyJson   string `json:"body_json"`
	ModifiedAt string `json:"modified_at"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateReleasePkgrel(ctx context.Context, arg UpdateReleasePkgrelParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateReleasePkgrel,
		arg.ArchPkgrel,
		arg.BodyJson,
		arg.ModifiedAt,
		arg.ID,
	)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.State,
		&i.SourceType,
		&i.VendorVersion,
		&i.OriginalFilename,
		&i.SourceSha256,
		&i.SourceArtifactID,
		&i.ArchPackageName,
		&i.ArchPkgrel,
		&i.BodyJson,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const updateRepoSettings = `-- name: UpdateRepoSettings :one
UPDATE repo_settings
SET revision = revision + 1,
    enabled = ?,
    listen_hosts = ?,
    listen_port = ?,
    advertised_url = ?,
    stable_enabled = ?,
    soak_seconds = ?,
    package_name_prefix = ?,
    trust_mode = ?,
    signing_fingerprint = ?,
    signing_initialized = ?,
    signing_pubkey_artifact_id = ?,
    root_pubkey_artifact_id = ?,
    root_fingerprint = ?,
    certified_pubkey_artifact_id = ?,
    keyring_gpg_artifact_id = ?,
    keyring_trusted_artifact_id = ?,
    keyring_revoked_artifact_id = ?,
    keyring_package_artifact_id = ?,
    keyring_package_sig_artifact_id = ?,
    keyring_version = ?,
    recovery_message = ?,
    modified_at = ?
WHERE id = 1 AND revision = ?
RETURNING id, revision, enabled, listen_hosts, listen_port, advertised_url, stable_enabled, soak_seconds, package_name_prefix, trust_mode, signing_fingerprint, signing_initialized, signing_pubkey_artifact_id, root_pubkey_artifact_id, root_fingerprint, certified_pubkey_artifact_id, keyring_gpg_artifact_id, keyring_trusted_artifact_id, keyring_revoked_artifact_id, keyring_package_artifact_id, keyring_package_sig_artifact_id, keyring_version, recovery_message, modified_at
`

type UpdateRepoSettingsParams struct {
	Enabled                     int64          `json:"enabled"`
	ListenHosts                 string         `json:"listen_hosts"`
	ListenPort                  int64          `json:"listen_port"`
	AdvertisedUrl               string         `json:"advertised_url"`
	StableEnabled               int64          `json:"stable_enabled"`
	SoakSeconds                 int64          `json:"soak_seconds"`
	PackageNamePrefix           string         `json:"package_name_prefix"`
	TrustMode                   string         `json:"trust_mode"`
	SigningFingerprint          string         `json:"signing_fingerprint"`
	SigningInitialized          int64          `json:"signing_initialized"`
	SigningPubkeyArtifactID     sql.NullString `json:"signing_pubkey_artifact_id"`
	RootPubkeyArtifactID        sql.NullString `json:"root_pubkey_artifact_id"`
	RootFingerprint             string         `json:"root_fingerprint"`
	CertifiedPubkeyArtifactID   sql.NullString `json:"certified_pubkey_artifact_id"`
	KeyringGpgArtifactID        sql.NullString `json:"keyring_gpg_artifact_id"`
	KeyringTrustedArtifactID    sql.NullString `json:"keyring_trusted_artifact_id"`
	KeyringRevokedArtifactID    sql.NullString `json:"keyring_revoked_artifact_id"`
	KeyringPackageArtifactID    sql.NullString `json:"keyring_package_artifact_id"`
	KeyringPackageSigArtifactID sql.NullString `json:"keyring_package_sig_artifact_id"`
	KeyringVersion              int64          `json:"keyring_version"`
	RecoveryMessage             string         `json:"recovery_message"`
	ModifiedAt                  string         `json:"modified_at"`
	Revision                    int64          `json:"revision"`
}

func (q *Queries) UpdateRepoSettings(ctx context.Context, arg UpdateRepoSettingsParams) (RepoSetting, error) {
	row := q.db.QueryRowContext(ctx, updateRepoSettings,
		arg.Enabled,
		arg.ListenHosts,
		arg.ListenPort,
		arg.AdvertisedUrl,
		arg.StableEnabled,
		arg.SoakSeconds,
		arg.PackageNamePrefix,
		arg.TrustMode,
		arg.SigningFingerprint,
		arg.SigningInitialized,
		arg.SigningPubkeyArtifactID,
		arg.RootPubkeyArtifactID,
		arg.RootFingerprint,
		arg.CertifiedPubkeyArtifactID,
		arg.KeyringGpgArtifactID,
		arg.KeyringTrustedArtifactID,
		arg.KeyringRevokedArtifactID,
		arg.KeyringPackageArtifactID,
		arg.KeyringPackageSigArtifactID,
		arg.KeyringVersion,
		arg.RecoveryMessage,
		arg.ModifiedAt,
		arg.Revision,
	)
	var i RepoSetting
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Enabled,
		&i.ListenHosts,
		&i.ListenPort,
		&i.AdvertisedUrl,
		&i.StableEnabled,
		&i.SoakSeconds,
		&i.PackageNamePrefix,
		&i.TrustMode,
		&i.SigningFingerprint,
		&i.SigningInitialized,
		&i.SigningPubkeyArtifactID,
		&i.RootPubkeyArtifactID,
		&i.RootFingerprint,
		&i.CertifiedPubkeyArtifactID,
		&i.KeyringGpgArtifactID,
		&i.KeyringTrustedArtifactID,
		&i.KeyringRevokedArtifactID,
		&i.KeyringPackageArtifactID,
		&i.KeyringPackageSigArtifactID,
		&i.KeyringVersion,
		&i.RecoveryMessage,
		&i.ModifiedAt,
	)
	return i, err
}

const updateRepoTrust = `-- name: UpdateRepoTrust :one
UPDATE repo_settings
SET revision = revision + 1,
    trust_mode = ?,
    signing_fingerprint = ?,
    signing_initialized = ?,
    signing_pubkey_artifact_id = ?,
    root_pubkey_artifact_id = ?,
    root_fingerprint = ?,
    certified_pubkey_artifact_id = ?,
    keyring_gpg_artifact_id = ?,
    keyring_trusted_artifact_id = ?,
    keyring_revoked_artifact_id = ?,
    keyring_package_artifact_id = ?,
    keyring_package_sig_artifact_id = ?,
    keyring_version = ?,
    recovery_message = ?,
    modified_at = ?
WHERE id = 1
RETURNING id, revision, enabled, listen_hosts, listen_port, advertised_url, stable_enabled, soak_seconds, package_name_prefix, trust_mode, signing_fingerprint, signing_initialized, signing_pubkey_artifact_id, root_pubkey_artifact_id, root_fingerprint, certified_pubkey_artifact_id, keyring_gpg_artifact_id, keyring_trusted_artifact_id, keyring_revoked_artifact_id, keyring_package_artifact_id, keyring_package_sig_artifact_id, keyring_version, recovery_message, modified_at
`

type UpdateRepoTrustParams struct {
	TrustMode                   string         `json:"trust_mode"`
	SigningFingerprint          string         `json:"signing_fingerprint"`
	SigningInitialized          int64          `json:"signing_initialized"`
	SigningPubkeyArtifactID     sql.NullString `json:"signing_pubkey_artifact_id"`
	RootPubkeyArtifactID        sql.NullString `json:"root_pubkey_artifact_id"`
	RootFingerprint             string         `json:"root_fingerprint"`
	CertifiedPubkeyArtifactID   sql.NullString `json:"certified_pubkey_artifact_id"`
	KeyringGpgArtifactID        sql.NullString `json:"keyring_gpg_artifact_id"`
	KeyringTrustedArtifactID    sql.NullString `json:"keyring_trusted_artifact_id"`
	KeyringRevokedArtifactID    sql.NullString `json:"keyring_revoked_artifact_id"`
	KeyringPackageArtifactID    sql.NullString `json:"keyring_package_artifact_id"`
	KeyringPackageSigArtifactID sql.NullString `json:"keyring_package_sig_artifact_id"`
	KeyringVersion              int64          `json:"keyring_version"`
	RecoveryMessage             string         `json:"recovery_message"`
	ModifiedAt                  string         `json:"modified_at"`
}

func (q *Queries) UpdateRepoTrust(ctx context.Context, arg UpdateRepoTrustParams) (RepoSetting, error) {
	row := q.db.QueryRowContext(ctx, updateRepoTrust,
		arg.TrustMode,
		arg.SigningFingerprint,
		arg.SigningInitialized,
		arg.SigningPubkeyArtifactID,
		arg.RootPubkeyArtifactID,
		arg.RootFingerprint,
		arg.CertifiedPubkeyArtifactID,
		arg.KeyringGpgArtifactID,
		arg.KeyringTrustedArtifactID,
		arg.KeyringRevokedArtifactID,
		arg.KeyringPackageArtifactID,
		arg.KeyringPackageSigArtifactID,
		arg.KeyringVersion,
		arg.RecoveryMessage,
		arg.ModifiedAt,
	)
	var i RepoSetting
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.Enabled,
		&i.ListenHosts,
		&i.ListenPort,
		&i.AdvertisedUrl,
		&i.StableEnabled,
		&i.SoakSeconds,
		&i.PackageNamePrefix,
		&i.TrustMode,
		&i.SigningFingerprint,
		&i.SigningInitialized,
		&i.SigningPubkeyArtifactID,
		&i.RootPubkeyArtifactID,
		&i.RootFingerprint,
		&i.CertifiedPubkeyArtifactID,
		&i.KeyringGpgArtifactID,
		&i.KeyringTrustedArtifactID,
		&i.KeyringRevokedArtifactID,
		&i.KeyringPackageArtifactID,
		&i.KeyringPackageSigArtifactID,
		&i.KeyringVersion,
		&i.RecoveryMessage,
		&i.ModifiedAt,
	)
	return i, err
}

const updateSoakStatus = `-- name: UpdateSoakStatus :exec
UPDATE repo_soaks SET status = ? WHERE pkgname = ? AND arch = ? AND pkgver = ?
`

type UpdateSoakStatusParams struct {
	Status  string `json:"status"`
	Pkgname string `json:"pkgname"`
	Arch    string `json:"arch"`
	Pkgver  string `json:"pkgver"`
}

func (q *Queries) UpdateSoakStatus(ctx context.Context, arg UpdateSoakStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSoakStatus,
		arg.Status,
		arg.Pkgname,
		arg.Arch,
		arg.Pkgver,
	)
	return err
}

const upsertChannelEntry = `-- name: UpsertChannelEntry :exec
INSERT INTO repo_channel_entries (
    channel, arch, pkgname, project_id, release_id, epoch, pkgver, pkgrel,
    artifact_id, sig_artifact_id, filename, published_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (channel, arch, pkgname) DO UPDATE SET
    project_id = excluded.project_id,
    release_id = excluded.release_id,
    epoch = excluded.epoch,
    pkgver = excluded.pkgver,
    pkgrel = excluded.pkgrel,
    artifact_id = excluded.artifact_id,
    sig_artifact_id = excluded.sig_artifact_id,
    filename = excluded.filename,
    published_at = excluded.published_at
`

type UpsertChannelEntryParams struct {
	Channel       string         `json:"channel"`
	Arch          string         `json:"arch"`
	Pkgname       string         `json:"pkgname"`
	ProjectID     sql.NullString `json:"project_id"`
	ReleaseID     sql.NullString `json:"release_id"`
	Epoch         int64          `json:"epoch"`
	Pkgver        string         `json:"pkgver"`
	Pkgrel        string         `json:"pkgrel"`
	ArtifactID    string         `json:"artifact_id"`
	SigArtifactID sql.NullString `json:"sig_artifact_id"`
	Filename      string         `json:"filename"`
	PublishedAt   string         `json:"published_at"`
}

func (q *Queries) UpsertChannelEntry(ctx context.Context, arg UpsertChannelEntryParams) error {
	_, err := q.db.ExecContext(ctx, upsertChannelEntry,
		arg.Channel,
		arg.Arch,
		arg.Pkgname,
		arg.ProjectID,
		arg.ReleaseID,
		arg.Epoch,
		arg.Pkgver,
		arg.Pkgrel,
		arg.ArtifactID,
		arg.SigArtifactID,
		arg.Filename,
		arg.PublishedAt,
	)
	return err
}

const upsertProjectRepoPolicy = `-- name: UpsertProjectRepoPolicy :exec
INSERT INTO project_repo_policies (
    project_id, stable_enabled, automatic_soak, soak_seconds_override
)
VALUES (?, 1, ?, ?)
ON CONFLICT (project_id) DO UPDATE SET
    stable_enabled = excluded.stable_enabled,
    automatic_soak = excluded.automatic_soak,
    soak_seconds_override = excluded.soak_seconds_override
`

type UpsertProjectRepoPolicyParams struct {
	ProjectID           string `json:"project_id"`
	AutomaticSoak       int64  `json:"automatic_soak"`
	SoakSecondsOverride int64  `json:"soak_seconds_override"`
}

func (q *Queries) UpsertProjectRepoPolicy(ctx context.Context, arg UpsertProjectRepoPolicyParams) error {
	_, err := q.db.ExecContext(ctx, upsertProjectRepoPolicy, arg.ProjectID, arg.AutomaticSoak, arg.SoakSecondsOverride)
	return err
}

const upsertRepoDatabase = `-- name: UpsertRepoDatabase :exec
INSERT INTO repo_databases (
    channel, arch, db_artifact_id, db_sig_artifact_id, files_artifact_id,
    files_sig_artifact_id, generated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (channel, arch) DO UPDATE SET
    db_artifact_id = excluded.db_artifact_id,
    db_sig_artifact_id = excluded.db_sig_artifact_id,
    files_artifact_id = excluded.files_artifact_id,
    files_sig_artifact_id = excluded.files_sig_artifact_id,
    generated_at = excluded.generated_at
`

type UpsertRepoDatabaseParams struct {
	Channel            string         `json:"channel"`
	Arch               string         `json:"arch"`
	DbArtifactID       string         `json:"db_artifact_id"`
	DbSigArtifactID    sql.NullString `json:"db_sig_artifact_id"`
	FilesArtifactID    sql.NullString `json:"files_artifact_id"`
	FilesSigArtifactID sql.NullString `json:"files_sig_artifact_id"`
	GeneratedAt        string         `json:"generated_at"`
}

func (q *Queries) UpsertRepoDatabase(ctx context.Context, arg UpsertRepoDatabaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepoDatabase,
		arg.Channel,
		arg.Arch,
		arg.DbArtifactID,
		arg.DbSigArtifactID,
		arg.FilesArtifactID,
		arg.FilesSigArtifactID,
		arg.GeneratedAt,
	)
	return err
}

const upsertSoak = `-- name: UpsertSoak :exec
INSERT INTO repo_soaks (
    pkgname, arch, pkgver, project_id, release_id, epoch, pkgrel, artifact_id,
    sig_artifact_id, soak_started_at, eligible_at, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (pkgname, arch, pkgver) DO UPDATE SET
    project_id = excluded.project_id,
    release_id = excluded.release_id,
    epoch = excluded.epoch,
    pkgrel = excluded.pkgrel,
    artifact_id = excluded.artifact_id,
    sig_artifact_id = excluded.sig_artifact_id,
    soak_started_at = excluded.soak_started_at,
    eligible_at = excluded.eligible_at,
    status = excluded.status
`

type UpsertSoakParams struct {
	Pkgname       string         `json:"pkgname"`
	Arch          string         `json:"arch"`
	Pkgver        string         `json:"pkgver"`
	ProjectID     sql.NullString `json:"project_id"`
	ReleaseID     sql.NullString `json:"release_id"`
	Epoch         int64          `json:"epoch"`
	Pkgrel        string         `json:"pkgrel"`
	ArtifactID    string         `json:"artifact_id"`
	SigArtifactID sql.NullString `json:"sig_artifact_id"`
	SoakStartedAt string         `json:"soak_started_at"`
	EligibleAt    string         `json:"eligible_at"`
	Status        string         `json:"status"`
}

func (q *Queries) UpsertSoak(ctx context.Context, arg UpsertSoakParams) error {
	_, err := q.db.ExecContext(ctx, upsertSoak,
		arg.Pkgname,
		arg.Arch,
		arg.Pkgver,
		arg.ProjectID,
		arg.ReleaseID,
		arg.Epoch,
		arg.Pkgrel,
		arg.ArtifactID,
		arg.SigArtifactID,
		arg.SoakStartedAt,
		arg.EligibleAt,
		arg.Status,
	)
	return err
}
