// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server.sql

package sqlcdb

import (
	"context"
)

const getServerState = `-- name: GetServerState :one
SELECT id, created_at, schema_kind, secret_backend, pki_ready,
       listen_enabled, listen_port, listen_hosts
FROM server_state
WHERE id = 1
`

func (q *Queries) GetServerState(ctx context.Context) (ServerState, error) {
	row := q.db.QueryRowContext(ctx, getServerState)
	var i ServerState
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SchemaKind,
		&i.SecretBackend,
		&i.PkiReady,
		&i.ListenEnabled,
		&i.ListenPort,
		&i.ListenHosts,
	)
	return i, err
}

const insertServerState = `-- name: InsertServerState :exec
INSERT INTO server_state (id, created_at, schema_kind, secret_backend, pki_ready)
VALUES (1, ?, ?, ?, ?)
`

type InsertServerStateParams struct {
	CreatedAt     string `json:"created_at"`
	SchemaKind    string `json:"schema_kind"`
	SecretBackend string `json:"secret_backend"`
	PkiReady      int64  `json:"pki_ready"`
}

func (q *Queries) InsertServerState(ctx context.Context, arg InsertServerStateParams) error {
	_, err := q.db.ExecContext(ctx, insertServerState,
		arg.CreatedAt,
		arg.SchemaKind,
		arg.SecretBackend,
		arg.PkiReady,
	)
	return err
}

const updateServerBackend = `-- name: UpdateServerBackend :exec
UPDATE server_state
SET secret_backend = ?, pki_ready = ?
WHERE id = 1
`

type UpdateServerBackendParams struct {
	SecretBackend string `json:"secret_backend"`
	PkiReady      int64  `json:"pki_ready"`
}

func (q *Queries) UpdateServerBackend(ctx context.Context, arg UpdateServerBackendParams) error {
	_, err := q.db.ExecContext(ctx, updateServerBackend, arg.SecretBackend, arg.PkiReady)
	return err
}

const updateServerListen = `-- name: UpdateServerListen :exec
UPDATE server_state
SET listen_enabled = ?, listen_port = ?, listen_hosts = ?
WHERE id = 1
`

type UpdateServerListenParams struct {
	ListenEnabled int64  `json:"listen_enabled"`
	ListenPort    int64  `json:"listen_port"`
	ListenHosts   string `json:"listen_hosts"`
}

func (q *Queries) UpdateServerListen(ctx context.Context, arg UpdateServerListenParams) error {
	_, err := q.db.ExecContext(ctx, updateServerListen, arg.ListenEnabled, arg.ListenPort, arg.ListenHosts)
	return err
}
