// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlcdb

import (
	"context"
)

const getLibrarySettings = `-- name: GetLibrarySettings :one
SELECT id, revision, ai_provider, ai_model, ai_reasoning_effort, ai_execution_mode, ai_auto_resolve, updates_enabled, updates_daily, updates_weekday, updates_hour, updates_minute, updates_auto_prepare, retained_package_versions, retained_complete_releases FROM library_settings WHERE id = 1
`

func (q *Queries) GetLibrarySettings(ctx context.Context) (LibrarySetting, error) {
	row := q.db.QueryRowContext(ctx, getLibrarySettings)
	var i LibrarySetting
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AiProvider,
		&i.AiModel,
		&i.AiReasoningEffort,
		&i.AiExecutionMode,
		&i.AiAutoResolve,
		&i.UpdatesEnabled,
		&i.UpdatesDaily,
		&i.UpdatesWeekday,
		&i.UpdatesHour,
		&i.UpdatesMinute,
		&i.UpdatesAutoPrepare,
		&i.RetainedPackageVersions,
		&i.RetainedCompleteReleases,
	)
	return i, err
}

const updateLibrarySettings = `-- name: UpdateLibrarySettings :one
UPDATE library_settings
SET revision = revision + 1,
    ai_provider = ?,
    ai_model = ?,
    ai_reasoning_effort = ?,
    ai_execution_mode = ?,
    ai_auto_resolve = ?,
    updates_enabled = ?,
    updates_daily = ?,
    updates_weekday = ?,
    updates_hour = ?,
    updates_minute = ?,
    updates_auto_prepare = ?,
    retained_package_versions = ?,
    retained_complete_releases = ?
WHERE id = 1 AND revision = ?
RETURNING id, revision, ai_provider, ai_model, ai_reasoning_effort, ai_execution_mode, ai_auto_resolve, updates_enabled, updates_daily, updates_weekday, updates_hour, updates_minute, updates_auto_prepare, retained_package_versions, retained_complete_releases
`

type UpdateLibrarySettingsParams struct {
	AiProvider               string `json:"ai_provider"`
	AiModel                  string `json:"ai_model"`
	AiReasoningEffort        string `json:"ai_reasoning_effort"`
	AiExecutionMode          string `json:"ai_execution_mode"`
	AiAutoResolve            int64  `json:"ai_auto_resolve"`
	UpdatesEnabled           int64  `json:"updates_enabled"`
	UpdatesDaily             int64  `json:"updates_daily"`
	UpdatesWeekday           int64  `json:"updates_weekday"`
	UpdatesHour              int64  `json:"updates_hour"`
	UpdatesMinute            int64  `json:"updates_minute"`
	UpdatesAutoPrepare       int64  `json:"updates_auto_prepare"`
	RetainedPackageVersions  int64  `json:"retained_package_versions"`
	RetainedCompleteReleases int64  `json:"retained_complete_releases"`
	Revision                 int64  `json:"revision"`
}

func (q *Queries) UpdateLibrarySettings(ctx context.Context, arg UpdateLibrarySettingsParams) (LibrarySetting, error) {
	row := q.db.QueryRowContext(ctx, updateLibrarySettings,
		arg.AiProvider,
		arg.AiModel,
		arg.AiReasoningEffort,
		arg.AiExecutionMode,
		arg.AiAutoResolve,
		arg.UpdatesEnabled,
		arg.UpdatesDaily,
		arg.UpdatesWeekday,
		arg.UpdatesHour,
		arg.UpdatesMinute,
		arg.UpdatesAutoPrepare,
		arg.RetainedPackageVersions,
		arg.RetainedCompleteReleases,
		arg.Revision,
	)
	var i LibrarySetting
	err := row.Scan(
		&i.ID,
		&i.Revision,
		&i.AiProvider,
		&i.AiModel,
		&i.AiReasoningEffort,
		&i.AiExecutionMode,
		&i.AiAutoResolve,
		&i.UpdatesEnabled,
		&i.UpdatesDaily,
		&i.UpdatesWeekday,
		&i.UpdatesHour,
		&i.UpdatesMinute,
		&i.UpdatesAutoPrepare,
		&i.RetainedPackageVersions,
		&i.RetainedCompleteReleases,
	)
	return i, err
}
