// Package recipe generates PacSmith PKGBUILD files and pacsmith.vars identity
// files from an inspected release, and validates Arch .install scripts without
// executing them.
package recipe

import (
	"path"
	"strconv"
	"strings"
)

// Generate returns a PKGBUILD that sources pacsmith.vars for per-release
// identity. Untrusted paths are quoted the same way as the C++ generator.
func Generate(rel Release) string {
	seen := make(map[string]struct{})
	var dependencies []string
	for _, dependency := range rel.Dependencies {
		if dependency.Status != MappingResolved || dependency.ArchPackage == "" ||
			dependency.Ignored || dependency.Bundled || dependency.Provided {
			continue
		}
		if _, ok := seen[dependency.ArchPackage]; ok {
			continue
		}
		dependencies = append(dependencies, ShellQuote(dependency.ArchPackage))
		seen[dependency.ArchPackage] = struct{}{}
	}
	for _, dependency := range rel.PackageMetadata.AdditionalDependencies {
		dependency = strings.TrimSpace(dependency)
		if dependency == "" {
			continue
		}
		if _, ok := seen[dependency]; ok {
			continue
		}
		dependencies = append(dependencies, ShellQuote(dependency))
		seen[dependency] = struct{}{}
	}

	var b strings.Builder
	b.WriteString("# Generated by PacSmith. This PKGBUILD belongs to you; review it before building.\n")
	b.WriteString("# Imported lifecycle scripts are data and are never executed automatically.\n")
	b.WriteString("# Per-release identity lives in pacsmith.vars and is rewritten for each vendor artifact.\n")
	b.WriteString("source \"${startdir:-.}/" + IdentityVariablesFile + "\"\n")
	b.WriteString("pkgname=\"${_PACSMITH_PKGNAME}\"\n")
	b.WriteString("pkgver=\"${_PACSMITH_PKGVER}\"\n")
	b.WriteString("pkgrel=\"${_PACSMITH_PKGREL}\"\n")
	b.WriteString("[[ -n ${_PACSMITH_EPOCH} ]] && epoch=\"${_PACSMITH_EPOCH}\"\n")
	b.WriteString("pkgdesc=\"${_PACSMITH_PKGDESC}\"\n")
	b.WriteString("arch=(\"${_PACSMITH_ARCH}\")\n")
	b.WriteString("url=\"${_PACSMITH_URL}\"\n")
	b.WriteString("license=(\"${_PACSMITH_LICENSES[@]}\")\n")
	b.WriteString("depends=(")
	b.WriteString(strings.Join(dependencies, " "))
	b.WriteString(")\n")
	b.WriteString("provides=(\"${_PACSMITH_PROVIDES[@]}\")\n")
	b.WriteString("conflicts=(\"${_PACSMITH_CONFLICTS[@]}\")\n")
	b.WriteString("if [[ -n ${_PACSMITH_COMPAT_PKGNAME} ]]; then\n")
	b.WriteString("  provides+=(\"${_PACSMITH_COMPAT_PKGNAME}=${pkgver}\")\n")
	b.WriteString("  conflicts+=(\"${_PACSMITH_COMPAT_PKGNAME}\")\n")
	b.WriteString("fi\n")
	if rel.resolvedSourceType() == SourceAppImage {
		b.WriteString("makedepends=('squashfs-tools')\n")
	}
	// makepkg strip/debugedit rewrite vendor ELF files and can break packed
	// payloads. PacSmith only repackages prebuilt artifacts.
	b.WriteString("options=('!strip' '!debug')\n")
	b.WriteString("xdata=(\n")
	b.WriteString("  'pacsmith.schema=1'\n")
	b.WriteString("  \"pacsmith.project=${_PACSMITH_PROJECT}\"\n")
	b.WriteString("  \"pacsmith.release=${_PACSMITH_RELEASE}\"\n")
	b.WriteString("  \"pacsmith.acquisition=${_PACSMITH_ACQUISITION}\"\n")
	b.WriteString("  \"pacsmith.source=${_PACSMITH_SOURCE_IDENTITY}\"\n")
	b.WriteString("  \"pacsmith.artifact=${_PACSMITH_ARTIFACT}\"\n")
	b.WriteString("  \"pacsmith.sha256=${_PACSMITH_SHA256}\"\n")
	b.WriteString(")\n")
	// ProjectStore maintains a visible relative symlink beside the PKGBUILD
	// because makepkg only searches local sources by basename. The
	// authoritative vendor file remains under sources/.
	b.WriteString("source=(\"${_PACSMITH_SOURCE}\")\n")
	b.WriteString("sha256sums=(\"${_PACSMITH_SHA256}\")\n")
	b.WriteString("if [[ -n ${_PACSMITH_ICON} ]]; then\n")
	b.WriteString("  source+=(\"${_PACSMITH_ICON}\")\n")
	b.WriteString("  sha256sums+=(\"${_PACSMITH_ICON_SHA256}\")\n")
	b.WriteString("fi\n")
	b.WriteString("noextract=(\"${_PACSMITH_SOURCE}\")\n")
	b.WriteString("[[ -n ${_PACSMITH_INSTALL} ]] && install=\"${_PACSMITH_INSTALL}\"\n\n")
	b.WriteString("package() {\n")
	appendExtraction(&b, rel)
	appendPayloadExclusions(&b, rel)
	appendLaunchers(&b, rel)
	appendAppRunOverlay(&b, rel)
	appendDesktopEntries(&b, rel)
	appendSelectedIcon(&b, rel)
	b.WriteString("}\n")
	return b.String()
}

// IdentityVariables returns the pacsmith.vars assignment block. Percent-encoded
// xdata values live here so the PKGBUILD can expand them without re-encoding.
func IdentityVariables(rel Release) string {
	epoch, version := SplitEpochAndVersion(rel.Debian.Version)
	description := firstLine(rel.PackageMetadata.Description)
	install := ""
	if rel.Lifecycle.Contents != "" && rel.Lifecycle.ValidationPassed {
		install = rel.Lifecycle.FileName
	}
	iconName := iconSourceName(rel)
	iconSHA := ""
	if iconName != "" {
		iconSHA = rel.InstallMapping.Icon.SHA256
	}
	offset := ""
	if rel.resolvedSourceType() == SourceAppImage {
		offset = strconv.FormatInt(rel.InstallMapping.AppImageOffset, 10)
	}

	var b strings.Builder
	b.WriteString("# PacSmith-owned release identity. Do not edit; rewritten for each vendor artifact.\n")
	appendAssignment(&b, "_PACSMITH_PKGNAME", rel.ArchPackageName)
	appendAssignment(&b, "_PACSMITH_COMPAT_PKGNAME", rel.CompatPackageName)
	appendArray(&b, "_PACSMITH_LICENSES", rel.PackageMetadata.Licenses)
	appendArray(&b, "_PACSMITH_PROVIDES", rel.PackageMetadata.Provides)
	appendArray(&b, "_PACSMITH_CONFLICTS", rel.PackageMetadata.Conflicts)
	appendAssignment(&b, "_PACSMITH_PKGVER", version)
	appendAssignment(&b, "_PACSMITH_PKGREL", pkgrelValue(rel))
	appendAssignment(&b, "_PACSMITH_EPOCH", epoch)
	if description == "" {
		description = rel.DisplayName
	}
	appendAssignment(&b, "_PACSMITH_PKGDESC", description)
	appendAssignment(&b, "_PACSMITH_ARCH", TranslateArchitecture(rel.Debian.Architecture))
	appendAssignment(&b, "_PACSMITH_URL", rel.PackageMetadata.Homepage)
	appendAssignment(&b, "_PACSMITH_SOURCE", rel.OriginalSourceFilename)
	appendAssignment(&b, "_PACSMITH_SHA256", rel.SourceSHA256)
	appendAssignment(&b, "_PACSMITH_PROJECT", percentEncode(rel.ProjectID))
	appendAssignment(&b, "_PACSMITH_RELEASE", percentEncode(rel.ID))
	appendAssignment(&b, "_PACSMITH_ACQUISITION", rel.Acquisition.kindName())
	appendAssignment(&b, "_PACSMITH_SOURCE_IDENTITY", percentEncode(sourceIdentityValue(rel)))
	appendAssignment(&b, "_PACSMITH_ARTIFACT", string(rel.resolvedSourceType()))
	appendAssignment(&b, "_PACSMITH_OPT", rel.optDirectory())
	appendAssignment(&b, "_PACSMITH_ICON", iconName)
	appendAssignment(&b, "_PACSMITH_ICON_SHA256", iconSHA)
	appendAssignment(&b, "_PACSMITH_APPIMAGE_OFFSET", offset)
	appendAssignment(&b, "_PACSMITH_INSTALL", install)
	return b.String()
}

// InstalledPayloadPath maps an inspected payload path onto the path it will
// have inside $pkgdir after package().
func InstalledPayloadPath(rel Release, payloadPath string) string {
	p := payloadPath
	src := rel.resolvedSourceType()
	if src == SourceArchive && rel.InstallMapping.archiveLayout() == ArchiveOptBundle {
		if rel.InstallMapping.StripCommonPrefix && rel.InstallMapping.CommonPrefix != "" {
			prefix := rel.InstallMapping.CommonPrefix + "/"
			p = strings.TrimPrefix(p, prefix)
		}
		return "/opt/" + rel.optDirectory() + "/" + p
	}
	if src == SourceAppImage {
		return "/opt/" + rel.optDirectory() + "/" + p
	}
	if src == SourceELF {
		if rel.InstallMapping.BinaryDestination == "" {
			return "/usr/bin/" + rel.ArchPackageName
		}
		return rel.InstallMapping.BinaryDestination
	}
	if strings.HasPrefix(p, "/") {
		return p
	}
	return "/" + p
}

// Validate checks PKGBUILD structure without executing it.
func Validate(contents string) string {
	var problems []string
	required := []string{"pkgname=", "pkgver=", "pkgrel=", "arch=(", "source=(", "sha256sums=(", "package()"}
	for _, field := range required {
		if !strings.Contains(contents, field) {
			problems = append(problems, "Missing "+field)
		}
	}
	depth := 0
	for _, character := range contents {
		switch character {
		case '{':
			depth++
		case '}':
			depth--
		}
		if depth < 0 {
			break
		}
	}
	if depth != 0 {
		problems = append(problems, "Unbalanced braces")
	}
	if len(problems) > 0 {
		return strings.Join(problems, "\n")
	}
	message := "Basic structural validation passed (the file was not executed)."
	if !strings.Contains(contents, IdentityVariablesFile) && !strings.Contains(contents, "_PACSMITH_") {
		message += "\nThis recipe does not use PacSmith identity variables; pkgver, the vendor filename, and checksums will go stale on the next vendor version."
	}
	return message
}

func appendAssignment(b *strings.Builder, name, value string) {
	b.WriteString(name)
	b.WriteByte('=')
	b.WriteString(ShellQuote(value))
	b.WriteByte('\n')
}

func appendArray(b *strings.Builder, name string, values []string) {
	b.WriteString(name)
	b.WriteString("=(")
	for i, value := range values {
		if i > 0 {
			b.WriteByte(' ')
		}
		b.WriteString(ShellQuote(value))
	}
	b.WriteString(")\n")
}

func appendExtraction(b *strings.Builder, rel Release) {
	switch rel.resolvedSourceType() {
	case SourceDebian:
		b.WriteString("  local data_archive=''\n")
		b.WriteString("  while IFS= read -r member; do\n")
		b.WriteString("    case \"$member\" in\n")
		b.WriteString("      data.tar|data.tar.*) data_archive=\"$member\"; break ;;\n")
		b.WriteString("    esac\n")
		b.WriteString("  done < <(bsdtar -tf \"$srcdir/${_PACSMITH_SOURCE}\")\n")
		b.WriteString("  if [[ -z \"$data_archive\" ]]; then\n")
		b.WriteString("    error 'Debian data archive was not found'\n")
		b.WriteString("    return 1\n")
		b.WriteString("  fi\n")
		b.WriteString("  bsdtar -xOf \"$srcdir/${_PACSMITH_SOURCE}\" \"$data_archive\" | bsdtar -xpf - --no-same-owner -C \"$pkgdir\"\n")
	case SourceRPM:
		// libarchive treats the RPM container as a filter and exposes its cpio
		// payload without requiring rpm2cpio or executing any package content.
		b.WriteString("  bsdtar -xpf \"$srcdir/${_PACSMITH_SOURCE}\" --no-same-owner -C \"$pkgdir\"\n")
	case SourceArchPackage:
		b.WriteString("  bsdtar -xpf \"$srcdir/${_PACSMITH_SOURCE}\" --no-same-owner -C \"$pkgdir\" \\\n")
		b.WriteString("    --exclude './.PKGINFO' --exclude '.PKGINFO' \\\n")
		b.WriteString("    --exclude './.BUILDINFO' --exclude '.BUILDINFO' \\\n")
		b.WriteString("    --exclude './.MTREE' --exclude '.MTREE' \\\n")
		b.WriteString("    --exclude './.INSTALL' --exclude '.INSTALL'\n")
	case SourceArchive:
		if rel.InstallMapping.archiveLayout() == ArchivePreserveRoot {
			b.WriteString("  bsdtar -xpf \"$srcdir/${_PACSMITH_SOURCE}\" --no-same-owner -C \"$pkgdir\"\n")
			return
		}
		strip := ""
		if rel.InstallMapping.StripCommonPrefix && rel.InstallMapping.CommonPrefix != "" {
			strip = " --strip-components 1"
		}
		b.WriteString("  install -d \"$pkgdir/opt/${_PACSMITH_OPT}\"\n")
		b.WriteString("  bsdtar -xpf \"$srcdir/${_PACSMITH_SOURCE}\" --no-same-owner")
		b.WriteString(strip)
		b.WriteString(" -C \"$pkgdir/opt/${_PACSMITH_OPT}\"\n")
	case SourceAppImage:
		b.WriteString("  # Preserve the complete AppDir below /opt; host integration is emitted separately.\n")
		b.WriteString("  install -d \"$pkgdir/opt/${_PACSMITH_OPT}\"\n")
		b.WriteString("  unsquashfs -no-progress -no-xattrs -f -o ${_PACSMITH_APPIMAGE_OFFSET} -d \"$pkgdir/opt/${_PACSMITH_OPT}\" \"$srcdir/${_PACSMITH_SOURCE}\"\n")
		b.WriteString("  find \"$pkgdir/opt/${_PACSMITH_OPT}\" -type f -exec chmod u-s,g-s {} +\n")
	case SourceELF:
		selectedDestination := rel.InstallMapping.BinaryDestination
		for _, launcher := range rel.InstallMapping.Launchers {
			if launcher.Enabled && !launcher.Missing {
				selectedDestination = launcher.Destination
				break
			}
		}
		if selectedDestination == "" {
			b.WriteString("  install -Dm755 \"$srcdir/${_PACSMITH_SOURCE}\" \"$pkgdir/usr/bin/${_PACSMITH_PKGNAME}\"\n")
		} else {
			b.WriteString("  install -Dm755 \"$srcdir/${_PACSMITH_SOURCE}\" \"$pkgdir")
			b.WriteString(doubleQuotedPath(selectedDestination))
			b.WriteString("\"\n")
		}
	}
}

func appendPayloadExclusions(b *strings.Builder, rel Release) {
	// A decomposed AppImage remains an intact AppDir under /opt. Its internal
	// etc/, usr/, and runtime paths are private bundle paths, not host paths,
	// and selectively pruning them invalidates the vendor runtime contract.
	if rel.resolvedSourceType() == SourceAppImage || len(rel.PayloadRules) == 0 {
		return
	}
	b.WriteString("\n  # Payload files excluded after PacSmith review.\n")
	for _, rule := range rel.PayloadRules {
		if !rule.Excluded {
			continue
		}
		b.WriteString("  rm -rf -- \"${pkgdir}/")
		b.WriteString(doubleQuotedPath(rule.Path))
		b.WriteString("\"\n")
	}
}

func appendLaunchers(b *strings.Builder, rel Release) {
	// Standalone ELF sources are installed directly at the selected command
	// destination below; emitting a second link would replace that executable.
	if rel.resolvedSourceType() == SourceELF {
		return
	}
	for _, launcher := range rel.InstallMapping.Launchers {
		if !launcher.Enabled || launcher.Missing || launcher.SourcePath == "" ||
			launcher.CommandName == "" {
			continue
		}
		destination := launcher.Destination
		if destination == "" {
			destination = "/usr/bin/" + launcher.CommandName
		}
		b.WriteString("\n  # Expose inspected payload command ")
		b.WriteString(launcher.CommandName)
		b.WriteString(".\n")
		b.WriteString("  install -d \"$pkgdir")
		b.WriteString(doubleQuotedPath(path.Dir(destination)))
		b.WriteString("\"\n")
		target := InstalledPayloadPath(rel, launcher.SourcePath)
		// DEB/RPM/root-layout archives commonly already install their command
		// at exactly the requested destination. Replacing it with a symlink to
		// itself would destroy the executable during package assembly.
		if launcher.kind() == LauncherSymlink && target == destination {
			continue
		}
		if launcher.kind() == LauncherWrapper || rel.resolvedSourceType() == SourceAppImage {
			if rel.resolvedSourceType() == SourceAppImage {
				// Keep APPIMAGE unset so the extracted AppDir cannot self-update
				// or act as a FUSE-mounted AppImage. The heredoc is unquoted so
				// _PACSMITH_OPT expands at makepkg time; runtime shell
				// parameters are escaped.
				execTarget := withOptVariable(target, rel.optDirectory())
				b.WriteString("  cat > \"$pkgdir")
				b.WriteString(doubleQuotedPath(destination))
				b.WriteString("\" <<PACSMITH_LAUNCHER\n")
				b.WriteString("#!/bin/sh\n")
				b.WriteString("APPDIR='/opt/${_PACSMITH_OPT}'\nexport APPDIR\nOWD=\"\\$PWD\"\nexport OWD\n")
				b.WriteString("ARGV0=\"\\$0\"\nexport ARGV0\nunset APPIMAGE\n")
				b.WriteString("exec \"")
				b.WriteString(doubleQuotedExpandable(execTarget))
				b.WriteString("\" \"\\$@\"\n")
			} else {
				b.WriteString("  cat > \"$pkgdir")
				b.WriteString(doubleQuotedPath(destination))
				b.WriteString("\" <<'PACSMITH_LAUNCHER'\n")
				b.WriteString("#!/bin/sh\n")
				b.WriteString("exec \"")
				b.WriteString(doubleQuotedPath(target))
				b.WriteString("\" \"$@\"\n")
			}
			b.WriteString("PACSMITH_LAUNCHER\n")
			b.WriteString("  chmod 0755 \"$pkgdir")
			b.WriteString(doubleQuotedPath(destination))
			b.WriteString("\"\n")
			continue
		}
		// /usr/bin/<name> -> ../../opt/<bundle>/<path>; relative links keep
		// the package relocatable while it is assembled under $pkgdir.
		variablePath := withOptVariable(target, rel.optDirectory())
		expandable := strings.Contains(variablePath, `${_PACSMITH_OPT}`)
		var relativeTarget string
		if expandable {
			relativeTarget = "../.." + variablePath
		} else if strings.HasPrefix(target, "/opt/") {
			relativeTarget = "../../" + target[1:]
		} else {
			relativeTarget = target
		}
		b.WriteString("  ln -sf ")
		if expandable {
			b.WriteByte('"')
			b.WriteString(doubleQuotedExpandable(relativeTarget))
			b.WriteByte('"')
		} else {
			b.WriteString(ShellQuote(relativeTarget))
		}
		b.WriteString(" \"$pkgdir")
		b.WriteString(doubleQuotedPath(destination))
		b.WriteString("\"\n")
	}
}

func appendAppRunOverlay(b *strings.Builder, rel Release) {
	if rel.resolvedSourceType() != SourceAppImage {
		return
	}
	appRun := rel.InstallMapping.AppRun
	if !appRun.Script || !appRun.UserModified || appRun.Contents == "" ||
		appRun.Contents == appRun.OriginalContents {
		return
	}
	b.WriteString("\n  # Overlay the reviewed AppRun entry point onto the extracted AppDir.\n")
	b.WriteString("  printf '%s' ")
	b.WriteString(ShellQuote(appRun.Contents))
	b.WriteString(" > \"$pkgdir/opt/${_PACSMITH_OPT}/AppRun\"\n")
	b.WriteString("  chmod 0755 \"$pkgdir/opt/${_PACSMITH_OPT}/AppRun\"\n")
}

func appendDesktopEntries(b *strings.Builder, rel Release) {
	for _, desktop := range rel.InstallMapping.DesktopEntries {
		destination := desktop.Destination
		if destination == "" {
			destination = "/usr/share/applications/" + desktop.ID + ".desktop"
		}
		if !desktop.Enabled {
			// Disabled AppImage candidates were never installed into the host
			// namespace. Leave their original copies untouched inside AppDir.
			if rel.resolvedSourceType() == SourceAppImage {
				continue
			}
			if desktop.SourcePath != "" {
				b.WriteString("  rm -f -- \"$pkgdir/")
				b.WriteString(doubleQuotedPath(desktop.SourcePath))
				b.WriteString("\"\n")
			}
			b.WriteString("  rm -f -- \"$pkgdir")
			b.WriteString(doubleQuotedPath(destination))
			b.WriteString("\"\n")
			continue
		}
		if desktop.Contents == "" {
			continue
		}
		b.WriteString("\n  # Install the reviewed desktop entry ")
		b.WriteString(desktop.ID)
		b.WriteString(".\n")
		b.WriteString("  install -d \"$pkgdir")
		b.WriteString(doubleQuotedPath(path.Dir(destination)))
		b.WriteString("\"\n")
		b.WriteString("  printf '%s' ")
		b.WriteString(ShellQuote(desktop.Contents))
		b.WriteString(" > \"$pkgdir")
		b.WriteString(doubleQuotedPath(destination))
		b.WriteString("\"\n")
		b.WriteString("  chmod 0644 \"$pkgdir")
		b.WriteString(doubleQuotedPath(destination))
		b.WriteString("\"\n")
		sourceInstalled := ""
		if desktop.SourcePath != "" {
			sourceInstalled = InstalledPayloadPath(rel, desktop.SourcePath)
		}
		if rel.resolvedSourceType() != SourceAppImage && sourceInstalled != "" &&
			sourceInstalled != destination {
			b.WriteString("  rm -f -- \"$pkgdir")
			b.WriteString(doubleQuotedPath(sourceInstalled))
			b.WriteString("\"\n")
		}
	}
}

func appendSelectedIcon(b *strings.Builder, rel Release) {
	icon := rel.InstallMapping.Icon
	extension := iconExtension(icon)
	if icon.Missing || icon.SHA256 == "" || icon.IconName == "" || extension == "" {
		return
	}
	directory := "/usr/share/icons/hicolor/256x256/apps"
	if extension == "svg" {
		directory = "/usr/share/icons/hicolor/scalable/apps"
	}
	b.WriteString("\n  # Install the selected, content-addressed application icon.\n")
	b.WriteString("  install -Dm644 \"$srcdir/${_PACSMITH_ICON}\" \"$pkgdir")
	b.WriteString(doubleQuotedPath(directory))
	b.WriteByte('/')
	b.WriteString(doubleQuotedPath(icon.IconName))
	b.WriteByte('.')
	b.WriteString(doubleQuotedPath(extension))
	b.WriteString("\"\n")
}

func withOptVariable(p, opt string) string {
	prefix := "/opt/" + opt
	if p == prefix {
		return "/opt/${_PACSMITH_OPT}"
	}
	if strings.HasPrefix(p, prefix+"/") {
		return "/opt/${_PACSMITH_OPT}/" + p[len(prefix)+1:]
	}
	return p
}

func IconSourceName(rel Release) string {
	return iconSourceName(rel)
}

func iconSourceName(rel Release) string {
	icon := rel.InstallMapping.Icon
	if icon.Missing || icon.SHA256 == "" {
		return ""
	}
	extension := iconExtension(icon)
	if extension == "" {
		return ""
	}
	return "pacsmith-icon." + extension
}

func iconExtension(icon Icon) string {
	extension := strings.ToLower(icon.Format)
	if extension == "" {
		extension = extOf(icon.ProjectPath)
	}
	if extension == "" {
		extension = extOf(icon.SourcePath)
	}
	return extension
}

func pkgrelValue(rel Release) string {
	if rel.ArchPkgrelOverride != "" {
		return rel.ArchPkgrelOverride
	}
	return strconv.Itoa(max(1, rel.ArchPkgrel))
}

func sourceIdentityValue(rel Release) string {
	if rel.Acquisition.CanonicalIdentity == "" {
		return "local:" + rel.SourceSHA256
	}
	return rel.Acquisition.CanonicalIdentity
}

func firstLine(value string) string {
	if i := strings.IndexByte(value, '\n'); i >= 0 {
		value = value[:i]
	}
	return strings.TrimSpace(value)
}

func extOf(p string) string {
	return strings.TrimPrefix(strings.ToLower(path.Ext(path.Clean(strings.ReplaceAll(p, "\\", "/")))), ".")
}
