#pragma once

#include "gui/main_window/main_window.hpp"
#include "gui/main_window/help_widgets.hpp"
#include "gui/main_window/project_list_delegate.hpp"
#include "gui/main_window/support.hpp"


#include "core/pkgbuild_generator.hpp"
#include "core/domain_validation.hpp"
#include "core/pkgbuild_install_plan.hpp"
#include "core/lifecycle_validator.hpp"
#include "core/repository_trust.hpp"
#include "core/system_package_query.hpp"
#include "core/payload_inspector.hpp"
#include "core/payload_review.hpp"
#include "core/package_artifact.hpp"
#include "core/background_updates.hpp"
#include "core/path_safety.hpp"
#include "core/managed_package.hpp"
#include "gui/command_progress_dialog.hpp"
#include "gui/desktop_entry_highlighter.hpp"
#include "gui/gui_instance.hpp"
#include "gui/import_worker.hpp"
#include "gui/pkgbuild_highlighter.hpp"
#include "gui/reanalyze_worker.hpp"
#include "gui/shell_highlighter.hpp"

#include <QAbstractItemView>
#include <QAbstractButton>
#include <QAction>
#include <QButtonGroup>
#include <QApplication>
#include <QColor>
#include <QComboBox>
#include <QCompleter>
#include <QCursor>
#include <QDate>
#include <QCloseEvent>
#include <QCheckBox>
#include <QClipboard>
#include <QCoreApplication>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDesktopServices>
#include <QDir>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QFileDialog>
#include <QFile>
#include <QFileInfo>
#include <QFontDatabase>
#include <QFormLayout>
#include <QFrame>
#include <QGroupBox>
#include <QHash>
#include <QHeaderView>
#include <QHBoxLayout>
#include <QHostInfo>
#include <QIcon>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QKeySequence>
#include <QFutureWatcher>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QListWidgetItem>
#include <QLocale>
#include <QMap>
#include <QMenu>
#include <QMessageBox>
#include <QMimeData>
#include <QNetworkAccessManager>
#include <QNetworkInterface>
#include <QNetworkReply>
#include <QNetworkRequest>
#include <QInputDialog>
#include <QPlainTextEdit>
#include <QPointer>
#include <QPainter>
#include <QPen>
#include <QProcess>
#include <QProgressDialog>
#include <QProgressBar>
#include <QRadioButton>
#include <QRegularExpression>
#include <QSaveFile>
#include <QScrollArea>
#include <QScopedValueRollback>
#include <QPixmap>
#include <QPushButton>
#include <QSizePolicy>
#include <QSignalBlocker>
#include <QSet>
#include <QSplitter>
#include <QStandardItemModel>
#include <QStandardPaths>
#include <QStatusBar>
#include <QStyle>
#include <QStyledItemDelegate>
#include <QStyleOptionViewItem>
#include <QSysInfo>
#include <QTableWidget>
#include <QTableWidgetItem>
#include <QTabWidget>
#include <QTabBar>
#include <QTimeEdit>
#include <QSpinBox>
#include <QStackedWidget>
#include <QSystemTrayIcon>
#include <QTextCursor>
#include <QThread>
#include <QThreadPool>
#include <QTimer>
#include <QTreeWidget>
#include <QTreeWidgetItemIterator>
#include <QUrl>
#include <QVBoxLayout>
#include <QWindow>
#include <QtConcurrentRun>

#include <algorithm>
#include <climits>
#include <filesystem>
#include <functional>
#include <memory>
#include <utility>
