ALTER TABLE jobs ADD COLUMN message TEXT NOT NULL DEFAULT '';
ALTER TABLE jobs ADD COLUMN current INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN total INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN failed_items INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN paused_items INTEGER NOT NULL DEFAULT 0;
