package repo

import (
	"archive/tar"
	"bytes"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/klauspost/compress/zstd"
)

type PackageInfo struct {
	Name     string
	Epoch    int64
	Pkgver   string
	Pkgrel   string
	Arch     string
	Filename string
}

func ParseFilename(name string) (PackageInfo, error) {
	name = strings.TrimSpace(name)
	for _, suffix := range []string{".pkg.tar.zst", ".pkg.tar.xz", ".pkg.tar.gz", ".pkg.tar.bz2", ".pkg.tar"} {
		if strings.HasSuffix(name, suffix) {
			name = strings.TrimSuffix(name, suffix)
			break
		}
	}
	parts := strings.Split(name, "-")
	if len(parts) < 4 {
		return PackageInfo{}, fmt.Errorf("invalid package filename %q", name)
	}
	arch := parts[len(parts)-1]
	pkgrel := parts[len(parts)-2]
	pkgver := parts[len(parts)-3]
	pkgname := strings.Join(parts[:len(parts)-3], "-")
	if pkgname == "" || pkgver == "" || pkgrel == "" || arch == "" {
		return PackageInfo{}, fmt.Errorf("invalid package filename")
	}
	return PackageInfo{Name: pkgname, Pkgver: pkgver, Pkgrel: pkgrel, Arch: arch, Filename: name}, nil
}

func ReadPKGINFO(r io.Reader) (PackageInfo, error) {
	decoder, err := zstd.NewReader(r)
	if err != nil {
		return PackageInfo{}, err
	}
	defer decoder.Close()
	tr := tar.NewReader(decoder)
	for {
		header, err := tr.Next()
		if err == io.EOF {
			break
		}
		if err != nil {
			return PackageInfo{}, err
		}
		name := strings.TrimPrefix(header.Name, "./")
		if name != ".PKGINFO" {
			continue
		}
		body, err := io.ReadAll(io.LimitReader(tr, 1<<20))
		if err != nil {
			return PackageInfo{}, err
		}
		return parsePKGINFO(body)
	}
	return PackageInfo{}, fmt.Errorf("package is missing .PKGINFO")
}

func parsePKGINFO(body []byte) (PackageInfo, error) {
	info := PackageInfo{}
	for _, line := range strings.Split(string(body), "\n") {
		key, value, ok := strings.Cut(line, " = ")
		if !ok {
			continue
		}
		switch key {
		case "pkgname":
			info.Name = strings.TrimSpace(value)
		case "pkgver":
			full := strings.TrimSpace(value)
			if colon := strings.IndexByte(full, ':'); colon > 0 {
				fmt.Sscan(full[:colon], &info.Epoch)
				full = full[colon+1:]
			}
			if dash := strings.LastIndexByte(full, '-'); dash > 0 {
				info.Pkgver = full[:dash]
				info.Pkgrel = full[dash+1:]
			} else {
				info.Pkgver = full
				info.Pkgrel = "1"
			}
		case "arch":
			info.Arch = strings.TrimSpace(value)
		}
	}
	if info.Name == "" || info.Pkgver == "" || info.Arch == "" {
		return PackageInfo{}, fmt.Errorf("incomplete .PKGINFO")
	}
	info.Filename = PackageFilename(info)
	return info, nil
}

func PackageFilename(info PackageInfo) string {
	return info.Name + "-" + info.Pkgver + "-" + info.Pkgrel + "-" + info.Arch + ".pkg.tar.zst"
}

func WritePackage(info PackageInfo, files map[string][]byte, install string) ([]byte, error) {
	if info.Pkgrel == "" {
		info.Pkgrel = "1"
	}
	if info.Arch == "" {
		info.Arch = "any"
	}
	pkgver := info.Pkgver + "-" + info.Pkgrel
	if info.Epoch > 0 {
		pkgver = fmt.Sprintf("%d:%s", info.Epoch, pkgver)
	}
	var pkginfo strings.Builder
	fmt.Fprintf(&pkginfo, "# Generated by PacSmith\n")
	fmt.Fprintf(&pkginfo, "pkgname = %s\n", info.Name)
	fmt.Fprintf(&pkginfo, "pkgbase = %s\n", info.Name)
	fmt.Fprintf(&pkginfo, "pkgver = %s\n", pkgver)
	fmt.Fprintf(&pkginfo, "pkgdesc = PacSmith repository package\n")
	fmt.Fprintf(&pkginfo, "url = https://github.com/anderson-arlen/pacsmith\n")
	fmt.Fprintf(&pkginfo, "builddate = %d\n", time.Now().Unix())
	fmt.Fprintf(&pkginfo, "packager = PacSmith <noreply@pacsmith.local>\n")
	fmt.Fprintf(&pkginfo, "size = 1\n")
	fmt.Fprintf(&pkginfo, "arch = %s\n", info.Arch)
	fmt.Fprintf(&pkginfo, "license = GPL\n")

	var buf bytes.Buffer
	encoder, err := zstd.NewWriter(&buf)
	if err != nil {
		return nil, err
	}
	tw := tar.NewWriter(encoder)
	write := func(name string, body []byte, mode int64) error {
		if err := tw.WriteHeader(&tar.Header{
			Name:     name,
			Mode:     mode,
			Size:     int64(len(body)),
			ModTime:  time.Unix(1, 0).UTC(),
			Typeflag: tar.TypeReg,
		}); err != nil {
			return err
		}
		_, err := tw.Write(body)
		return err
	}
	if err := write(".PKGINFO", []byte(pkginfo.String()), 0644); err != nil {
		return nil, err
	}
	if install != "" {
		if err := write(".INSTALL", []byte(install), 0644); err != nil {
			return nil, err
		}
	}
	for name, body := range files {
		name = strings.TrimPrefix(name, "/")
		if err := write(name, body, 0644); err != nil {
			return nil, err
		}
	}
	if err := tw.Close(); err != nil {
		return nil, err
	}
	if err := encoder.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}
